label chapter1:
    scene Hallway

    "Girl2" "Hey, Who's the creep?"
    "Girl1" "Why's she sneaking around like that?"
    "Girl2" "Maybe she's a spy on a secret mission!"
    #show Kanna
    Kan "You know I can hear you guys."
    Kan "I don't care what they say. No one can stop me from achieving my goals. I have resolved myself to claim my-"
    Rin "{i}Gasp!{/i} Air! I need air!"
    Kan "Get back in there! You're supposed to stay hidden!"
    Rin "Nah, I'm just messing with you. It's surprisingly comfy for a cramped place. I even get to write a bucket list for my retirement!"
    Kan "Hey! Is that my pen and notebook? Don't play around with that!"
    Rin "What else am I gonna do? Bore myself to death? I’ve done enough of that at the shrine."
    Kan "It's not my fault that- {i}Eep!{/i} It's Kyousuke!"
    Rin "That's... the Kyousuke you're looking at?"
    #ART CG? Kanna adores him while she imagines him being her prince charming. While Ringo's face is blank...
    Kan "Yes! Kyousuke! The glorious, the handsome, the one and only..."
    #Code Set the correct time in the wait tag, based on the VA performance.
    "He looks like…{w=0.5} the most boring looking person in the world."
    "Oh well, that just makes things easier!"
    Kan "The other day, I stole Kyousuke's yakisoba bread..."
    Rin "...Why?"
    Kan "It tasted like Kyousuke~"
    Rin "All right! I get it! God, are all teenagers this creepy? If you like him so much, then why not be honest with him?"
    Kan "I don't know. He- he makes me all fluttery!"
    Rin "Fluttery how?"
    Kan "I don't know! What if I say something stupid and offend him?! Or-"
    Rin "Jeez! Just go talk to him already!"
    Kan "What am I supposed to say?"
    Rin "It doesn't matter. Just start talking. He's right there waiting for you, come on, you got this!"
    Kan "O-okay... s-s-sure…. I-I-I-I got this..."
    Rin "Come on, take a step forward... that's it. Almost there, there you go-"
    "???" "Kyousuke!"
    Kan "Eep!"
    Kyou "Oh, good morning Maya. What's up?"
    Maya "I just wanted to see you, that's all."
    Kan "{i}Gasp!{/i}"
    Rin "Uh-oh."
    "Just when we're about to get started...Kanna is stopped dead in her tracks."
    Rin "Oh no.........."
    Kyou "See me? Do you want to see my math notes? Do you need me to help you finish your lunch again?"
    Maya "*Sigh* I don't want to go to volleyball today. If I’m gonna work hard everyday, it would be nice to have someone there to cheer me on~"
    Kyou "You mean like a fan club?"

    Maya "No I mean, I, er… maybe if boys were there to watch us play, the girls would perform better~"
    Kyou "But it’s an all-girls volleyball team. Why would guys be there?"
    Maya "No, Kyousuke, I mean-"
    # SFX School bell rings.
    "*Ding ding*"
    Maya "Nevermind. I gotta go to class. See you later!"
    "Is that my target? A brainless dork who can’t read a room?"
    "What does Kanna even see in him? And who the hell is this love interest appearing out of nowhere?"
    scene Bedroom
    "After school, we go back to Kanna's room. She's got a tray full of brownies from her cooking club. I help myself to them while Kanna is preoccupied."
    Kan "Urrrrrrrgggghhhhhhhhh!!!!!!!"
    "She's been screaming into that pillow since we got back."
    "How long is she planning to keep this up?"
    Kan "Who does she even think she is trying to steal my KYOUSUKE! You, spirit! Make her disappear!"
    Rin "{i}Sigh{/i} You know I can't do that."
    Kan "Why not?!"
    Rin "Look, kid. There are some things I can do, and some I can't. Killing people’s not in the job description."
    Kan "And somehow drinking all my Ramune is? I was saving those."
    Rin "{i}Gulp... gulp…{/i} Ah! Well anyway, it seems like you've got some competition. If we're going to defeat this Maya girl, I'm going to need to gather more information on both of them. "
    # Art (Sprite Artist) Ringo wears a hat or glasses
    Kan "What's with that getup?"
    Rin "I'm going under cover!"
    "I need to find out more about them in order to grant the wish. So I plan on doing some investigating while Kanna is at the club. I may need to use some magic for this one"
    "This would be easier if I still had my human form. I could pass as a student easily enough."
    "Oh well, as long as no one sees me, I should be fine."
    jump chapter2
