label charlottedate:
    # Update the day shown on the upper corner... to nothing!
    $ game_day = ""

    #Art BG festival
    #Fade into the festival background


    Rin "Man, I hate Kumamatsuri. Such a stupid festival."
    Kyou "But Mr. Guardian Angel, it only happens once a year! You should celebrate."
    Kyou "It is a festival all about bears! You should be happy!"
    Rin "You mean the festival where they throw a party about EATING a bear?"
    Kyou "That's what this is about?"
    Rin "Yes! What did you think it was about?"
    Kyou "I don't know, bear equality or something."
    Rin "You thought the bear shaped snacks, the bear themed games, and the bear themed decorations were about bear equality?"
    Kyou "Makes sense to me."
    Rin "So you eating those gummy bears is a show of equality to you?"
    Kyou "Sure, I don't see why not."
    Rin "So you're celebrating bears by RIPPING OFF THE HEADS OF THEIR GUMMY BROTHERS?"
    Kyou "For the record, I don't just eat gummy bears."
    Kyou "Gummy bears, gummy worms, gummy sharks, if there were gummy people, I'd eat them too."
    Kyou "I don't discriminate. I believe in fairness for all gummy snacks."
    Rin "Whatever. You're a hypocrite."
    Kyou "I thought you'd be happy Mr. Guardian Angel, both about Kumamatsuri and about me going on a date."
    Kyou "We finally landed a girlfriend and the whole town is here to celebrate my {i}beary{/i} best friend!"
    Rin "First off, if you ever say anything like that again I'm going to turn you into fish."
    Rin "Second, I wouldn't exactly call this a date. You put the note in her locker, but we don't even know if she got it or will show up."
    Rin "And third, I'M NOT A BEAR!"
    Kyou "Why wouldn't she come? Everyone agreed that I put the note in the locker, asking them out."
    Rin "Kid, kid, kid. You have so much to learn."
    Rin "You're going to spend the rest of your life being disappointed by other people over and over again."
    Rin "You think girls like it when you leave them cute little love notes?"
    Kyou "Y-yeah?"
    Rin "You think teenage girls will do what they say they will?"
    Kyou "M-maybe?"
    Rin "If she was going to come, don't you think she'd be here by now?"
    Rin "We've been here for an hour already, gorging ourselves on candy and junk food."
    Kyou "I'm almost out of gummies…"
    Rin "And you're almost out of gummies!"
    Rin "Do you really want to stick around here waiting for someone who's never going to show up?"
    Rin "Or do you want to hang out with someone you know for sure wants to be around you?"
    Kyou "Know for sure? What do you mean?"
    Rin "Listen kid, I'm not going to mess around anymore. Time for us to real talk."
    Kyou "Real talk? Has everything we've said before been fake talk?"
    Rin "Just stuff for it for a second and listen."
    Kyou "Stuff it? Aren't you already stuffed though?"
    Rin "SHUT UP AND LISTEN."
    Kyou "OK, OK, geez."
    Rin "I'm your Guardian Angel, I promised you I'd get you the girl of your dreams, didn't I?"
    Kyou "You did, you did."
    Rin "See I'm a bit of a uh…love guru. I know who's supposed to end up with who."
    Kyou "Like…you can tell who a person's soul mate is?"
    Rin "Er, yeah! Soul mates. I'm a soul mater. I know who you're destined to be with and who you'll be the most happy with."
    Kyou "I thought that was something that was up to fate?"
    Rin "Eh, fate's the exact same thing as luck, kid. And I'm the embodiment of luck!"
    Kyou "That doesn't seem fully right, if it's up to luck, how could you know people's soul mates?"
    Rin "D-don't get bogged down in semantics here. All you need to know is that you need to trust me. Alright?"
    Kyou "Well, alright. You are my guardian angel after all."
    Rin " OK, good. So listen up, I'm going to be completely straight with you."
    Kyou "Were you not straight before?"
    Rin "If you make one more joke kid I'm going to turn you into a gummy person and eat you myself."
    Kyou "Oooh, what do you think I'd taste like? I bet it's gonna be something awesome like electric blue raspberry."
    Rin "That is the flavor you'd be but that's not the point."
    Kyou "I've tried many other ways to do this kid, but now's the time to play it clean. There's someo-"
    Char "WAHAHAHA!"
    Rin "Oh my God, no…"
    Kyou "There she is! You said she wasn't coming, but I knew she would!"
    Kyou "What were you going to say, Mr. Guardian Angel?"
    Rin "Nothing. Don't worry about it."
    Kyou "You see, it is fate! I appreciate your help with finding me my soul mate!"
    Rin "What? NO NO NO THAT'S NOT-"
    #Enter Charlotte Sprite
    #Charlotte is calling for Kyousuke loudly and playfully.
    Char "Kyoooooooousuke~. I know you're around here somewhere, my seismic readings are going off the charts."
    Char "Either the tectonic plates of the earth are about to collide into each other, destroying all life as we know it. Or my wizard in training is around this area."
    #Same as before, Charlotte is calling for Kyousuke loudly and playfully.
    Char "And I'm going to just assume it's the second one but if it's not we're all doomed so I'm just going to hope that Kyoooooooousuke~, is somewhere here."

    Kyou "Charlotte! You made it!"
    Char "I did indeed. The night of Kumamatsuri is something I never, ever miss."
    Char "I do apologize for my tardiness, I was busy making a list for all the baubles we'll need for our mission."
    Kyou "Baubles? Mission? What mission?"
    Char "The tactical Kumamatsuri operation? Do you not remember?"
    Kyou "Uh…"
    Char "No matter! You will learn when the time comes."
    Kyou "Well if that's the case, what do you want to do first?"
    Char "Our first objective is to gather the necessary ingredients Kyousuke."
    Char "Babules, curiosities, elements, viscera, food stuffs, particles, we need things my fair Kyousuke."
    Kyou "So…we're going to the souvenir stands first?"
    Char "The souvenir stands! Of course, that makes sense, that makes sense. Much simpler than the original plan, but it's always much easier."
    Char "Which is good because I for one did not want to get covered in alien guts tonight."
    Char "TO THE MERCHANTS WE GO!"

    #Cut to Ringo
    Rin "Something isn't right here, what does that nutcase mean by {i}tactical Kumamatsuri operation?{/i}."
    Rin "I need to know what's going on before I go tell Kanna, we got one last shot at winning him over."
    Rin "I better follow them."

    #Fade transition to new scene.
    #Fade into the festival background to mimic transition.


    Char "Well Kyousuke, we're missing something."
    Kyou "Food. I think we're missing food."
    Kyou "I'm so hungry. And you took my last gummy bear for…whatever our mission is."
    Char "We needed him, Kyousuke. We need to sacrifice his gummy life force for the sake of the mission. We will meet him again in gummy valhalla, don't worry."
    Kyou "But I'm starving."
    Kyou "And we're right next to all the food stands!"
    Char "Be strong! Ignore your hunger pains and focus on the task at hand."
    Char "Pay no attention to the sweet and savory smells wafting past your nose."
    Char "Ignore the endless colors and richness of the meats and sweets on display."
    Char "Plug your ears to the sizzling grills and roaring fryers all around us."
    #Sizzling cook sounds
    Char "See that. Don't listen to that."
    Kyou "Ooooh Charlotte! My stomach is going to explode! I need food so badly. Real food, not the junk I was eating before."
    Char "Wait, Kyousuke, say that again."
    Kyou "That again."
    Char "Hold on, hold on, say it one more time."
    Kyou "It one more time."
    Char "I, that, again, need, food, not, real, junk, explode, Ooooh Charlotte."
    Char "Need, junk, not, explode, I, real, Ooooh Charlotte, again, that, food."
    Char "Hmmm…"
    Char "..."
    Kyou "..."
    Kyou "Uh…Charlotte?"
    Char "FIREWORKS!"
    Kyou "AHH. You scared me."
    Char "{i}Ooooh Charlotte, I need real explode, not that junk food again!{/i}"
    Char "Kyousuke you're a genius! You cracked the code! You just didn't say the words in the right order!"
    Kyou "I…what?"
    Char "{i}Ooooh Charlotte, I need real explode, not that junk food again.{/i} We don't need to sacrifice the gummy at all. A life force is just a soul after all. And we can mimic the passion and energy of a soul with an explosion."
    Char "And the fireworks are what set off my seismic readings earlier. Of course! The last piece of the puzzle we're missing was right in front of us this whole time. Good job Kyousuke!"
    Kyou "Thanks? But I don't understand what I did."
    Char "Fireworks, Kyousuke, fireworks."
    Char "Little packages of raw flame and dangerous gunpowder, exploding into the air and sending fizzling swirls of pure celestial firepower through the sky."
    Char "If only I could be so grossly incandescent."
    Kyou  "So you want to go to the fireworks show?"

    Char "No I don't want to {i}go{/i} to the fireworks show, we need fireworks ourselves."
    Char "It's very important for the mission we are on that we get fireworks."
    Char "Sparklers, rockets, smoke bombs, doesn't matter. We just need them."
    Kyou "You know, When I invited you to come to Kumamatsuri with me, I figured we'd do a lot more…Kumamatsuri like things."
    Kyou "We've been running around buying knick-knacks from the souvenir stands for hours now!"
    Kyou "When are we gonna get our munch on?"
    Char "They aren't just mere souvenirs Kyousuke. They're trinkets of great magical importance!"
    Char "Now that you're my wizard assistant, or wizzstant for short, we need to make sure you're properly prepared to handle any and all magic you're using."
    Char "Do you like exploding, Kyousuke?"
    Kyou "I don't know, I've never exploded before. But it doesn't sound like fun."
    Char "How about turning into a pile of goop?"
    Kyou "I've never been gooped before, but it doesn't sound like fun."
    Char "Well if you don't want to explode, get gooped, or worse, explode into goop, then I suggest you hold onto the trinkets so your magic is tethered to a low power object."
    Char "We'll get munching and crunching after our mission. First we get fireworks, then we head to the dimensional portal, complete our objective, and then we get our snack on at the festival."
    Kyou "What exactly is our mission again?"
    Char "That is on a need to know basis for now. You'll be debriefed once we reach the LZ."
    Kyou "LZ?"
    Char "Location of zion? Liquid zeal? Legendary zoetic? Landing zone? Come on Kyousuke, you should be familiar with this terminology by now."
    Char "But this time I'm referring to the location zone. At the proper time and the proper place, I'll let you know what the mission is."
    Kyou "I see. You're going for the whole 'mysterious, keep him on his toes, big surprise' kind of date."
    Kyou "Do you always have big surprises for the people you go on dates with?"
    Char "Date!? Kyousuke, you are my wizzstant and we're on an important mission. Right now we're getting trinkets so we can wield our magic with more control, later we will get subsistence so we can replenish ourselves so we can scout out the rest of what Kumamatsuri has to offer."
    Char "I'd hardly call this a {i}date{/i} as you humans say. I'm not even wearing the traditional shinbou monk relationship garb, essential for any and all {i}dates{/i} as you say."
    Kyou "You are wearing that yukata though. It looks really nice."
    Char "Why thank you. I have no idea what this thing was called. I had to fight off the transtemporal travel raptors for this {i}yakuza{/i} as you call it."
    Char "They only shaved off two dozen centuries of my life force too, most do not live to tell of their encounter with the transtemporal travel raptors."
    Kyou "I don't know what you just said. So I'm just going to say again that you look really nice Charlotte."
    Char "Why thank you again Kyousuke. Now let's go look for those fireworks!"
    Kyou "You got it!"

    #Cut to Ringo snooping

    Rin "Those two really do share one brain cell."
    Rin "What on earth are all those dumb little novelty gifts for?"
    Rin "And the last thing that lunatic needs is fireworks."
    Rin "I better keep on them."

    #Fade transition to new scene.
    #Fade into the festival background to mimic transition.

    Char "HOW IS THERE NO FIREWORKS ANYWHERE?"
    Char "We're at a festival, every single merchant should be selling them by the dozen, what is this?"
    Kyou "I don't think festival's really sell fireworks, they just use them for a huge demonstration."
    Kyou "I'm pretty sure we can't buy them, at least not around here."
    Char "Hmmm, where could we get gunpowder at this hour."
    Char "I could hop into the explosive barrel dimension and snag from gunpowder, but I need to save my magic for our concoction."
    Char "I could travel forward in time to where all of earth's energy drinks are replaced with pure gasoline. But I don't think there's enough clocks around here to time travel."
    Char "I could try to make my own explosive material, but I don't want to smelt all the baubles we bought earlier."
    Char "Looks like we only have one option, Kyousuke."
    Char "You said there's a fireworks show, right?"
    Kyou "That's right."
    Char "You thinking what I'm thinking? Looks like we're going to have to participate in the oldest tradition in all of the cosmos."
    Kyou "Chillin'?"
    Char "Close, but no. Bartering!"
    Char "We're going to have to trade something for a firework."
    Kyou "Trade? All I got is some pocket lint."
    Char "Oh! How much, how much?"
    Kyou "About a fistful."
    Char "That wouldn't do, we'll need at least two fist fulls to make the trade even."
    Kyou "You think we could just ask him for a small firework or something?"
    Char "Ask? Kyousuke, we are choosers, not beggars."
    Char "We must make an equivalent and fair exchange otherwise the explosive power of the gunpowder will diminish."
    Char "And of course, trading one of our magical baubles is just out of the question."
    Char "Hmmm, what to do, what to do."
    Char "Any ideas, Kyousuke?"
    Kyou "None whatsoever!"
    Char "That's alright, that's alright, you are a magical trainee after all. You gotta learn the ropes before moving into a full time position anyway."
    Char "Wait, we're at Kumamatsuri. There's challenges and prizes to win and earn here."
    Char "We must partake in one of these human trails and win ourselves an award. Then we trade that for a firework of some kind."
    Kyou "Are you sure that's the easiest way to get fireworks? We could leave and buy some at a store then come back."
    Char "And look like cowards to the runners of the contests? Olympic athletes swim in olympic pools Kyousuke! Not regular pools."
    Kyou "I don't think anyone will think we're cowards for leaving. In fact, I don't think anyone cares."
    Char "If these smug merchants want a competition, then they will have one!"
    Char "I've created entire planets with the snap of my fingers, regrown detached limbs with my potions, and rearrange the stars in the sky on a whim!"
    Char "Nothing is impossible for the interplanetary, interdimensional, interpersonal mad cosmic warlock that is Charlotte Von Vega!"
    Char "WAHAHAHA!"
    Char "..."
    Char "But I do struggle with challenges of physical skill so this one is up to you, Kyousuke!"
    Kyou "Wha? Me?"
    Char "Yes, wah, you!"
    Kyou "Didn't you just say nothing is impossible for you?"
    Char "Yep. I could accomplish the physical trails easily if I wanted to."
    Char "But my alter ego would have to awaken. And I do NOT want to mess with her right now."
    Kyou "Guess it's up to me then. I always won these kinds of games as a kid, I'm sure I got this in the bag!"
    Char "That's the spirit, Kyousuke! What level are your abilities?"
    Kyou "Abilities?"
    Char "Strength, perception, endurance, charisma, intelligence, agility, luck. You know, just the usual non-magic stats and abilities.. Nothing {i}special.{/i}"
    Kyou "Uh…five?"
    Char "Five? For all of them?"
    Kyou "Um…yeah for all of them."
    Char "You're the most average person alive Kyousuke!"
    Kyou "Thanks? I think?"
    Char "Kyousuke, the King of average! You stand above all others adequate, sufficient, acceptable, and good enough, as the pinnacle of averageness!"
    Kyou "Are…are you complimenting me or are you insulting me?"
    Char "Don't know but we're getting off track. Let's play a game and win a prize!"
    Kyou "I'm down to play anything. What do you want to play, Charlotte?"
    Char "I'm up for anything. How about we let the whims of fate decide!"
    Char "Kyousuke, may I see your fist-full-o'-lint?"
    Kyou "It's my lucky pocket lint, so be careful alright?"
    Char "Don't worry. Its entire existence in your pocket has led up to this moment."

    Char "BE FREE FIST-O'-LINT! GUIDE US TO OUR DESTINY!"
    Kyou "Hey! My pocket lint!"
    Char "Follow it, Kyousuke! The winds of fate now guide us to our challenge ahead!"

    #Cut to Ringo snooping
    Rin "I can feel my IQ dropping the longer I listen to them."
    Rin "They better do whatever they're going to do soon, otherwise my brain is going to rot away."
#Fade transition to new scene.
#Fade into the festival background to mimic transition.
    Char "There! The fist-o'-lint landed in that vat of water!"
    Char "It's filled with fish? Golden fish?"
    Char "OH GOD THEY'RE EATING FIST-O'-LINT!"
    Kyou "THEY'RE TEARING HIM TO SHREDS! STOP IT YOU MONSTERS!"
    Char "It's too late my median prince, he's gone. The ravenous golden serpents have devoured Fist-O'-Lint."
    Kyou "He's moved onto the giant pocket in the sky."
    Char "We should have a moment of silence for our fallen comrade."
    "..."
    "..."
    "..."
    Kyou "Hey, there's more lint in my pocket!"
    Char "Heh, looks like my regenerating spell worked. Pretty soon here Kyousuke, spec-o'-lint will soon grow again into his former abundance. We'll see our full grown friend soon."
    Char "He did guide us to this challenge, whatever it may be."
    Kyou "Oh, oh! This is the goldfish scooping game!"
    Kyou "You use this little scoopy thingy to pick up as many goldfish as you can and put them in a bowl."
    Kyou "Then you give the bowl to the stand owner and they put the fish in a bag and you get to keep them!"
    Kyou "The trick is that the net on the little scoop is made out of rice paper, so it dissolves if it stays in water too long."
    Kyou "But I think this game might be for kids though, we might be too old to play."
    Char "Kyousuke, we are but mere infants in the grand cosmos. The eye of creation has yet to even blink once for us."
    Kyou "No I mean like little little kids, like elementary schoolers."
    Char "Elementary schoolers, middle schoolers, high schoolers, a thaumaturge as old as the stars themself, what's the difference!"
    Char "We turn Fist-O'-Lint into Bag-O'-Fish and then we get ourselves some dyn-no-mite! A simple alteration of material. Piece of cake."
    Kyou "I don't know Charlotte. Do you really think the fireworks person would be willing to trade for a bag of goldfish?"

    Char "Kyousuke, are you telling me if someone walked up to you with a bag of golden fish, you wouldn't take it?"
    Kyou "...Good point, it's the perfect plan."
    Char "Grasp the scoop and begin scooping!"
    #Small water splash noise
    "..."
    Kyou "The net already dissolved…"
    Char "What? It was in there for like five seconds!"
    Kyou "It's alright, we can just grab another one."
    #Small water splash noise
    "..."
    Char "IT BROKE AGAIN!?"
    Kyou "I wasn't even anywhere near the fish…"
    Char "That's it. We're doing it Charlotte's way. Here, put this on."
    Kyou "The fox mask we bought earlier?"
    #If we need to change this sequence for the sake of art, we can do so!
    #Charlotte is now wearing a fox mask
    Char "Yes, put it on quickly!"
    #Kyousuke is now wearing a fox mask
    Kyou "Now what?"
    Char "We channel the great spirit of {i}Sionnach{/i} to help us retrieve a golden fish from the water."
    Char "O' Sionnach, proud hunter, master of tricks, wise woodland teacher, please grant us the dexterity and cunning needed in order to catch a golden fish."
    Kyou "..."
    Char "..."
    Kyou "D-did it work?"
    Char "YES, GRAB THE FISH NOW KYOUSUKE. GO GO GO."
    Kyou "AHHHHhh!"
    #Splashing around noises.
    Char "Keep going Kyousuke! The grace of Sionnach flows through you!"
    Kyou "I got one, I got one!"
    Char "Excellent! O' Sionnach, cunning explorer, champion of agility, thank you for the blessing you have bestowed upon us this day."
    Char "Take off your mask Kyousuke! Quick!"
    #Kyousuke removes the fox mask
    Kyou "Why do we have to be so fast about it?"
    #Charlotte removes the fox mask
    Char "Possession is not something you want to happen to you, Kyousuke."
    Char "Trust me on this one, it gets ugly real fast. Even when the spirit is friendly."
    Kyou "Have you ever been possessed by Charlotte?"
    Char "Oh yes, many times. Everytime I enter the ghost realm, in fact."
    Char "Never forget to turn on your Specter Vision Kyousuke. It can save your life."

    Kyou "Man, I can't even imagine what it would be like to take control of other people against their will."
    Kyou "Making decisions for them, making them do things they don't want to do, it's like some sort of nasty trick isn't it?"
    Char "..."
    Char "..."
    Kyou "Charlotte? You alright?"
    Char "Er, uh, um, hrmm."
    Kyou "Charlotte?"
    Char "I agree! Whole heartedly yes. Real bad juju with that kind of stuff. Shall we go make our exchange for the fireworks now?"
    Kyou "Sure! I still don't fully know how we'll get him to trade for this little goldfish."
    Char " I've trained in the art of charisma for eons, it'll be a piece of cake."
    Char "The firework merchant doesn't actually {i}need{/i} his fireworks. He {i}needs{/i} this golden fish. We just have to help him realize that!"
    Kyou "That makes sense…I think."
    Char "After we procure the firework, all we need to do is remove its gunpowder and then we have the final ingredient we need for our operation!"
    Char "We'll head right over to the LZ and begin our mission!"
    Kyou "What's our mission again?"
    Char "I'll fill you in when we get there!"
    Char "Onward!"
    Kyou "Onward!"

    #Cut back to Ringo

    Rin "Nothing good ever came from giving teenagers gunpowder."
    Rin "She's up to something bad. And she's dragging Kyousuke along with her."
    Rin "I've wasted enough time following them around all night, I better go get Kanna."



    #ART BG Shrine evening

    "We see the silhouettes of two teenagers standy by the shrine."
    #Same note as the previous notes. Should we have the narration?
    #ART only shows Kyousuke's sprite until Charlotte talks.



    Kyou "I can't believe you actually convinced that guy to trade us for the fish!"
    Char "Like I said Kyousuke, he just didn't know he needed it yet."
    Char "Now we have everything we need."
    Kyou "Wow, the moon sure is pretty tonight."
    Kyou "... But isn't the good luck shrine a weird place to go on a date?"
    Char "WAHAHAHA!"
    Char "Remember, Kyousuke, this isn't a date but a reconnaissance mission."
    Kyou "I'm surprised you wanted me to tag along, Charlotte. This isn't at all what I expected when I invited you to Kumamatsuri."
    Char "Well my eager apprentice, it only makes sense to come along on the magical operations I undertake. How else will you learn?"
    Kyou "True, but are you sure you need my help? What am I going to do?"
    Char "You're going to help me place a curse upon this shrine so no one can use it ever again!"
    Char "Then we're going to that food stand back at the festival that serves otherworldly crepes. But only after we accomplish our mission!"
    Kyou "Isn't it bad luck to put a curse on...good luck?"
    Char "Luck is a myth. Why wait for the universe to throw something your way, when you can make it happen yourself?"
    Kyou "Don't other people rely on luck, though?"
    Char "Oh, sure, but I am here to remove that safety net from society."
    Kyou "But I believe in luck..."
    Char "Trust me, my budding assistant, I'm all the luck you need ."


    #"Kanna and Ringo can be seen faintly, hiding in a bush in the background."
    #Again do we need the narration? How do we want to handle the narration throughout the entire game?
    # Transition effects to Kanna and Ringo talking

    "Kanna and Ringo can be seen faintly, hiding in a bush in the background."

    Rin "That freakin' demon fox is trying to curse me into being like this forever!"
    Rin "No wonder they needed the stupid gunpowder, those moroons are going to blow up the shrine!"
    Rin "That petty pompous pretentious punk! If I have to be stuck in this bear form any longer, I'm gonna act like one and rip his gorgeous head off."
    Rin "Ok, Kanna, we only have one shot at this, ready?"
    Rin "Kanna?"
    Kan "..."
    Kan "I really thought he was gonna ask me out..."
    Rin "Hey, the kid doesn't know what he wants. Plus, the fox and his walking insane asylum patient have been cheating this whole time."
    Kan "..."
    Kan "Haven't we been doing the same? Or just me, I guess... you only did your job"
    Kan "Maybe Kyousuke is better off with Charlotte......"
    Rin "HEY!"
    Kan "What?"
    Rin "You can't worry about that right now!"
    Rin "We have one shot at me retiring, you winning over Kyousuke, and saving the shrine."
    Rin "Do you really want to be that person who didn't risk it cause you're doubting yourself?"
    Kan "..."
    Rin "Well?"
    Kan "Ok."
    Kan "{i}Deep breath...{/i} Let's do it!"
    Rin "Atta girl! You got the sweater you made last night?"
    Kan "Yep!"
    Rin "Alright, you know what to do."

    "Ringo floats over to Kyousuke, hiding in his slightly open backpack."
    #same as other narration notes.

    Char "Ok, Kyousuke, did you bring the last ingredient?"

    Kyou "Yup! Luckily my house was on the way here, so I grabbed it super quick."
    Kyou "My dog can't even put his tongue back into his mouth, so getting saliva from him was easy!"
    Char "Excellent! Once I'm finished placing the baubles we've collected in the correct diagram, I will place the mixture on the steps of the shrine, you pour the saliva in, and then {b}BOOM{/b}!"
    Char "The mixture will bubble and erupt, splattering the shrine with the antithetical god's reverse potion!"
    Char "The shrine will lose all its mystical power, becoming just another historical building!"
    Char "WAHAHAHA!"
    Kyou "..."
    Kyou "That's cool but...why do we need my dog's saliva?"
    Char "It's the ingredient that allows the cola and stardust to combine with each other. I told you this earlier, remember?"
    Kyou "Can you list all the ingredients and what they do again?"
    Char "Alright, but only because I like to arbitrarily explain things."

  #Cut to Ringo in Kyousuke's bag.

    Rin "Come on, hurry it up. I know you're there."
    Youk "Did you think you would go unspotted, Mr. Fortune? Here to save your reputation?"
    Rin "Did you know I was following your unstable mistress around all night? Why didn't you show up and face me like a man?"
    Youk "Watching you embarrassed at Lady Charlotte and Kyousuke's evening was a delight. Why would I step in when it was so much fun to watch how uncomfortable you were?"
    Rin "Whatever, sicko! Why're you even here in the first place? Haven't you already granted her stupid wish?"
    Youk "Nearly. Once this date is over, then my job is complete."
    Youk "You're certainly aware that this is my idea, are you not?"
    Youk "Lady Charlotte didn't mind the embarrassment you caused her, she even forgave you. But I convinced her that revenge would be much sweeter."
    Rin "Come on, man, are you really that upset about the blanket thing?"
    Youk "Very. And cursing your shrine will amuse me much. I like your little bear form, it's quaint."
    Rin "You really are a demon! Not even a good one at that."
    Youk "Pardon?"
    Rin "Lemme guess, If I try to influence Kyousuke, you'll just overwrite his thinking, right?"
    Rin "Pretty lame, honestly."
    Rin "Guess you're that scared of me, huh?"
    Youk "I assure you, a little teddy bear is the least of my fears."
    Youk "I am of much higher status than you, Mr. Fortune; we both know that."
    Youk "I use my powers to get my way, just as you do."
    Rin "But you know he'll listen to me if you don't use your mind control trick."
    Rin "I don't rely on gimmicks like that. Guess I'm the smarter one here, huh?"
    Youk "Are you joking? I can best you, regardless of any limitations to my ability."
    Rin "Prove it."
    Youk "Come now, you're just trying to get a rise out of me to get the upper hand."
    Rin "Yep. Is it working?"
    Youk" Yes, quite so."
    Rin " Alright! Let's do this one more time, for all the marbles, Youko."
    Youk "Fine. But know the stakes: if I win, your shrine will lose its magic, you'll be stuck as a bear, and I'll turn you pink."
    Rin "Woah, woah, woah, who said anything about turning me pink!?"
    Youk "Because I want to. I think it would suit you."
    Rin "Whatever! If I win I won't ever have to see your stupid heart-throb face anymore, anyway."


   #Cut to Kyousuke and Charlotte.

    Char "And last, but not least, after pouring in the expired milk and cucumber dish soap, we add your dog's saliva into the mixture."
    Char "Which will cause the potion to explode, splattering all over the shrine!"
    Char "Destroying the idea of fortune, luck and all other concepts of prosperity!"
    Kyou "..."
    Kyou "That's cool and all, but we're still gonna go eat after this, right?"
    Char "Oh, absolutely, I'm starving!"
    Char "Now let's get this show on the road! Would you like to do the honors?"
    Kyou "Sure!"
    Char "Here's the potion, now place it on the shrine and work our magic!"


    #CODE
    # ART The usual VN choice GUI

    Rin "(Alright, Kanna is just about to distract them.)"
    Rin "(I need to make sure Kyousuke spills it before he reaches the shrine.)"
    Rin "(There's a stick on the ground... I could trip him.)"
    Rin "(But that might make the potion splash on the shrine.)"
    Rin "(Maybe I can have him ask Charlotte for help, distracting them for a minute...?)"
    Rin "(But that would only buy us time, I'm not sure it would do much...)"
    Rin "(Gah, this one's tricky!)"
    menu:
        "Choices to send to Kyousuke:"

        "Look at how pretty the moon is.":
            #Choice: "Look at how pretty the moon is."
            #Kanna good end.

            Kyou "Man, the moon really is beautiful tonight, isn't it."
            Char "It sure is. I visited it once, you know. Wasn't too bad."
            Char "But please, stay focused, Kyousu-"
            Kan "Kyousuke! Wait!"
            Kyou "What the? Kanna?"

            # ART Possible CG?
            "Kyousuke turns around to see Kanna running up to them. As Kyousuke turns around, he trips over the stick laying on the ground, launching the potion through the air... and splashing it  all over Charlotte."

            #SFX of Charlotte being splashed.

            Kyou "AHHH"
            Char "BAHHWAH!"
            Kan "Omigosh, are you guys alright?"
            Kyou "I'm alright. Charlotte, I'm sorry, are you ok?"
            Char "..."
            Kan "I'm so sorry you guys, I didn't mean for this to happen. I just came to see Kyousuke. I have something to tell him, and something to give him."
            Kyou "Charlotte, you smell surprisingly good."
            Kyou "I thought this stuff would stink for sure."
            Char "..."
            Kan " Charlotte?"
            Char "..."
            Char "...ha."
            Char "..."
            Char "WAHAHAHA!"
            Char "WAHAHAHAHAHAHAHA!"
            Kyou "{i}Uh oh{/i}, I think she went crazy."
            Char "I thought I mixed all the ingredients properly! Turns out I forgot about the most important one."
            Kan "Love?"
            Char "Nope! Sulfur!"
            Char "Good thing I forgot, I suppose, otherwise I would be goo right now."
            Char "Well, Kanna, as a mage that's been around for a few hundred millennia, I know when I'm beaten."
            Kan "Wha?"
            Char "Kyousuke! You are fired!"
            Kyou "Wha?"
            Char "Let me tell you, Kanna, this whole experience has been fun! But It seems you desire Kyousuke much more than I do."
            Kan "Really? I didn't really do anything, I just came here to try and stop you guys."
            Char "Most girls would have admitted defeat and moved on. Yet, here you are, trying to stop my plans and win back Kyousuke."
            Char "And since I have melted butter in my hair currently, I'd say you succeeded."
            Char "Actually, I'm kind of a fan, it makes my hair feel a lot smoother!"
            Char "Return to Kumamatsuri and be merry."
            Kyou "You could come with us, Charlotte."
            Char "Ohhoho! I appreciate the gesture, but I'm not sure I'd fit the mood. Besides, I got to wash this potion off, and start looking into a new assistant"
            Kan "Um, I made this sweater for Kyousuke, but you should have it instead. You shouldn't walk home covered in that icky, paint like goo."
            Kan "It says 'cool dude', but just ignore that."
            Char " It's so sweet you think Kyousuke's cool, Kanna. But I think this sweater fits me better."
            Char "WAHAHAHA!"
            Char "Well, I bid you two {i}adieu{/i}."
            Kan "Bye, Charlotte."
            Kyou "Bye!"

            Kyou "I don't really get what's happening."
            Kan "Kyousuke, I have something to tell you."
            Kyou "What's up?"
            Kan " Kyousuke I..."
            Kan "I think that..."
            Kan " You're really..."
            Kan "You see, this whole time I've…"
            Kan "..."
            Kyou "I don't want to cut you off or anything Kanna. But all I can think of is crepes."
            Kyou "You want to head back to the festival and get some?"
            Kan "I, uh…"
            Kan "Well, sure. That sounds nice."
            Kyou "Wicked, I'm so hungry. Let's go!"


            #Cut to Ringo and Youko
            Rin "Welp, that's that, I suppose."
            Rin "Any thoughts, Youko?"
            Youk "Well played, Mr.Fortune."
            Rin "That's it?"
            Youk "Like you said, that's that."


            #SFX Youko disappears into a poof of purple smoke/sparks.

            Rin "Another wish granted."
            Rin "The last wish granted, huh."

            #ART the screen slowly begins to fade into white.
            # SFX something angelic and subtle.

            Rin "What's happening?"
            Rin "My body is glowing."
            Rin "This feels amazing!"
            Rin "It's finally time! Oh baby, I've been waiting for this!"
            Rin "Next stop is paradise!"
            Rin "Thank you, Kanna."

            #End
        "What was I supposed to do again? Better ask Charlotte.":
            #Choice: ""What was I supposed to do again? Better ask Charlotte.""
            #Kanna bad end.

            Kyou "Hey, uh, what am I supposed to do again?"
            Char "Kyousuke! You place the potion, then pour the saliva into it!"
            Kyou "But which one do I do first again?"
            Kan "Kyousuke! Wait!"
            Kyou "What the? Kanna?"
            Kyou "WOOAH."

            "Kyousuke falls over, launching the potion into the air. The potion crashes back down, landing and spilling all over Kyousuke."
            #SFX of Kyousuke being splashed.

            Kan "Kyousuke! Are you alright?"
            Char"Stop, drop, and roll Kyousuke!"
            Kyou "Oooof."
            Kyou "Hey, this stuff doesn't smell too bad."
            Char "How strange, the potion should have turned Kyousuke into fine bolognese sauce."
            Char "I guess I forgot the most important ingredient."
            Kan "Love?"
            Char "Nope! Sulfur!"
            Char "Good thing I forgot it this time, I suppose."
            Char "WAHAHAHA!"
            Kan "I'm so sorry, Kyousuke."
            Kyou "It's alright, Kanna, why are you here anyway?"
            Kan "I..."
            Char "She's here to stop us from cursing the shrine!"
            Char "Well met, fair Kanna."
            Char "Gotta say, when I first met you, I didn't think you were capable of this sort of chicanery."
            Kan "Well, that's kind of true, I'm here to-"
            Char "Now, Kyousuke, we must get you to my domicile so I can give you the antidote!"
            Char "Otherwise your skin will turn purple... in about ten minutes."
            Kyou "What? I don't wanna be purple."
            Char "It's not so bad. I trained with the 'purple extraterrestrial heart and soul kinda dull, never full' ninjas a couple centuries ago."
            Kyou "The what?"
            Char "The purple extraterrestri-"
            Kan "Purple alien ninjas? I thought you trained with monks?"
            Char "Purple alien ninjas who played amazing jazz tunes, I miss them everyday. "
            Char "And remember, someone who has lived as long as me has trained with pretty much everyone."
            Char "They were all very nice... and purple."
            Kyou "As much as I love the non sequitur; I really, really don't want to be purple. It's like, my sixth least favorite color."
            Char " Well then, let's head to my extravagant home."
            Kan "W-w-wait! Kyousuke you can't go with Charlotte."
            Kan " I, I, I have something to tell you."
            Kyou "What is it Kanna?"
            Char "Make it quick! I can already see it tinting his skin."
            Kan "I..."
            Kan"..."
            Kan "I can't tell you like this."
            Kan "Nevermid, you guys gotta go."
            Kan "Here, I brought a sweater for you, Kyousuke."
            Kan "It says 'cool dude' on it."
            Kyou "Oh, thanks, Kanna! Why did you bring me a sweater?"
            Kan"J...just don't worry about it."
            Kyou "Alright! I won't!"
            Char "Are you sure you don't wish to be purple? Like I said, I know a certain group of ninjas that would take you in."
            Kyou "No way! Let's go fix this Charlotte."
            Kyou "Bye Kanna!"
            Kan " Bye..."
            Kan "...Kyousuke."

            #Cut to Ringo and Youko floating by the shrine.

            Youk "Well... that was... something."
            Rin "That might have been the stupidest conclusion I've ever seen."
            Youk "You're aware that Kyousuke going to Charlotte's house means I've won, correct?"
            Rin "Well, that's it, I guess. My perfect wish granting track record is gone, reduced to ashes in front of my eyes."
            Youk "Purple ashes."
            Rin "Oh, get bent!"
            Youk "I won't mess with your shrine anymore, Mr.Fortune, so you're free to start granting your next wish."
            Youk "I hope it takes a while for you to find your next wish though. Your bear form is simply adorable."
            Rin "Gee, thanks. I'm sooooo glad you think that."
            Rin "What about Kanna, though?"
            Youk "This is a cut throat business, you shouldn't grow so attached to your clients."
            Youk "But worry not, in a week she'll just be one more client in the millionths you served."
            Rin "I guess..."
            Youk "Take care, Mr.Fortune."
            Youk "I'm sure our paths will cross again."

            #SFX Youko disappears into a poof of purple smoke/sparks.

            "I drift over to Kanna, who's looking up into the night sky."

            Rin "Soooooo, that didn't exactly go as planned, huh?"
            Kan "..."
            Rin "You alright, kid?"
            Kan " I'm just waiting to fall off my bed."
            Rin " Huh?"
            Kan "This dream has been pretty crazy, but I don't think I like it anymore."
            Rin " Kid, it's not..."
            Rin "..."
            Rin " I'm sorry Kanna."
            Kan " It's alright, Mr. Bear."
            Kan "I always wake up from my dreams after I fall out of bed."

            #ART the screen slowly begins to fade into white(or black?).
            #End
            scene black with fade
return
