#ART BG Shrine evening

"We see the silhouettes of two teenagers standy by the shrine."

#ART only shows Kyousuke's sprite until Charlotte talks.

Kyou "Wow, the moon sure is pretty tonight."
Kyou "... But isn't the good luck shrine a weird place to go on a date?"
Char "WAHAHAHA!"
Char "Remember, Kyousuke, this isn't a date but a reconnaissance mission."
Kyou "I'm surprised you wanted me to tag along, Charlotte. Didn't you say this was a date, though?"
Char "I asked you to come with me as my assistant, to help me place a curse upon this shrine so no one can use it ever again!"
Char "We are also going to a late night cafe that has otherworldly scones. But only after we accomplish our mission!"
Kyou "Isn't it bad luck to put a curse on...good luck?"
Char "Luck is a myth.Why wait for the universe to throw something your way, when you can make it happen yourself?"
Kyou "Don't other people rely on luck, though?"
Char "Oh, sure, but I am here to remove that safety net from society."
Kyou "But I believe in luck..."
Char "Trust me, my budding assistant, I'm all the luck you need ."

"Kanna and Ringo can be seen faintly, hiding in a bush in the background."

Rin "That freakin' demon fox is trying to curse me into being like this forever!"
Rin "Petty asshole! If I have to be stuck in this bear form any longer, I'm gonna act like one and rip his gorgeous head off."
Rin "Ok, Kanna, we only have one shot at this, ready?"
Rin "Kanna?"
Kan "..."
Kan "I really thought he was gonna ask me out..."
Rin "Hey, the kid doesn't know what he wants.Plus, the fox and his walking insane asylum patient have been cheating this whole time."
Kan "..."
Kan "Haven't we been doing the same? Or just me, I guess... you only did your job"
Kan "Maybe Kyousuke is better off with Charlotte......"
Rin "HEY!"
Kan "What?"
Rin "You can't worry 'bout that right now!"
Rin "We have one shot at me retiring, you winning over Kyousuke, and saving the shrine."
Rin "Do you really want to be that person who didn't risk it 'cause you're doubting yourself?"
Kan "..."
Rin "Well?"
Kan "Ok."
Kan "{i}Deep breath...{/i} Let's do it!"
Rin "Atta girl! You got the sweater you made last night?"
Kan "Yep!"
Rin "Alright, you know what to do."

"Ringo floats over to Kyousuke, hiding in his slightly open backpack."

Char "Ok, Kyousuke, did you bring the last ingredient?"
Kyou "Yup! My dog can't even put his tongue back into his mouth, so getting saliva from him was easy!"
Char "Excellent! I will place the mixture on the steps of the shrine, you pour the saliva in, and {b}BOOM{/b}!"
Char "The mixture will bubble and erupt, splattering the shrine with the antithetical god's reverse potion!"
Char "The shrine will lose all its mystical power, becoming just another historical building!"
Char "WAHAHAHA!"
Kyou "..."
Kyou "That's cool but...why do we need my dog's saliva?"
Char "It's the ingredient that allows the cola and stardust to combine with each other. I told you this earlier, remember?"
Kyou "Can you list all the ingredients and what they do again?"
Char "Alright, but only because I like to arbitrarily explain things."

#Cut to Ringo in Kyousuke's bag.

Rin "Come on, hurry it up."
Youk "Did you think you would go unspotted, Mr. Fortune? Here to save your reputation?"
Rin "Why're you even here? Haven't you already granted her stupid wish?"
Youk "Nearly. Once this date is over, then my job is complete."
Youk "You're certainly aware that this is my idea, are you not?"
Youk "Miss Charlotte didn't mind the embarrassment  you caused her, she even forgave you. But I convinced her that revenge would be much sweeter"
Rin "Come on, man, are you really that upset about the blanket thing?"
Youk "Very. And cursing your shrine will amuse me much. I like your little bear form, it's quaint."
Rin "You really are a demon! Not even a good one at that."
Youk "Pardon?"
Rin "Lemme guess, If I try to influence Kyousuke, you'll just overwrite his thinking, right?"
Rin "Pretty lame, honestly."
Rin "Guess you're that scared of me, huh?"
Youk " I assure you, a little teddy bear is the least of my fears."
Youk "I am of much higher status than you, Mr. Fortune; we both know that."
Youk "I use my powers to get my way, just as you do."
Rin "But you know he'll listen to me if you don't use your mind control trick."
Rin "I don't rely on gimmicks like that. Guess I'm the smarter one here, huh?"
Youk "Are you joking? I can best you, regardless of any limitations to my ability."
Rin "Prove it."
Youk "Come now, you're just trying to get a rise out of me to get the upper hand."
Rin "Yep. Is it working?"
Youk" Yes, quite so."
Rin " Alright! Let's do this one more time, for all the marbles, Youko."
Youk "Fine. But know the stakes: if I win your shrine will lose it's magic, you'll be stuck as a bear, and I'll turn you pink."
Rin "Woah, woah, woah, who said anything about turning me pink!?"
Youk "Because I want to. I think it would suit you."
Rin "Whatever! If I win I won't ever have to see your stupid heart-throb face anymore, anyway."

#Cut to Kyousuke and Charlotte.

Char "And last, but not least, after pouring in the expired milk and cucumber dish soap, we add your dog's saliva into the mixture."
Char "Which will cause the potion to explode, splattering all over the shrine!"
Char "Destroying the idea of fortune, luck and all other concepts of prosperity!"
Kyou "..."
Kyou "That's cool and all, but we're still gonna go eat after this, right?"
Char "Oh, absolutely, I'm starving!"
Char "Now let's get this show on the road! Would you like to do the honors?"
Kyou "Sure!"
Char "Here's the potion, now place it on the shrine and work our magic!"

#CODE
# ART The usual VN choice GUI

Rin "(Alright, Kanna is just about to distract them.)"
Rin "(I need to make sure Kyousuke spills it before he reaches the shrine.)"
Rin "(There's a stick on the ground... I could trip him.)"
Rin "(But that might make the potion splash on the shrine.)"
Rin "(Maybe I can have him ask Charlotte for help, distracting them for a minute...?)"
Rin "(But that would only buy us time, I'm not sure it would do much...)"
Rin "(Gah, this one's tricky!)"
menu:
    "Choices to send to Kyousuke:"

    "Look at how pretty the moon is.":
        #Choice: "Look at how pretty the moon is."
        #Kanna good end.

        Kyou "Man, the moon sure is pretty tonight, isn't it."
        Char "It sure is. I visited it once, you know. Wasn't too bad."
        Char "But please, stay focused, Kyousu-"
        Kan "Kyousuke! Wait!"
        Kyou "What the? Kanna?"

        # ART Possible CG?
        "Kyousuke turns around to see Kanna running up to them. As Kyousuke turns around, he trips over the stick laying on the ground, launching the potion through the air... and splashing it  all over Charlotte."

        #SFX of Charlotte being splashed.

        Kyou "AHHH"
        Char "BAHHWAH!"
        Kan "Omigosh, are you guys alright?"
        Kyou "I'm alright. Charlotte, I'm sorry, are you ok?"
        Char "..."
        Kan "I'm so sorry you guys, I didn't mean for this to happen. I just came to see Kyousuke. I have something to tell him, and something to give him."
        Kyou "Charlotte, you smell surprisingly good."
        Kyou "I thought this stuff would stink for sure."
        Char "..."
        Kan " Charlotte?"
        Char "..."
        Char "...ha."
        Char "..."
        Char "WAHAHAHA!"
        Char "WAHAHAHAHAHAHAHA!"
        Kyou "{i}Uh oh{/i}, I think she went crazy."
        Char "I thought I mixed all the ingredients properly! Turns out I forgot about the most important one."
        Kan "Love?"
        Char "Nope! Sulfur!"
        Char "Good thing I forgot, I suppose, otherwise I would be goo right now."
        Char "Well, Kanna, as a mage that's been around for a few hundred millennia, I know when I'm beaten."
        Kan "Wha?"
        Char "Kyousuke! You are fired!"
        Kyou "Wha?"
        Char "Let me tell you, Kanna, this whole experience has been fun! But It seems you desire Kyousuke much more than I do."
        Kan "Really? I didn't really do anything, I just came here to try and stop you guys."
        Char "Most girls would have admitted defeat and moved on. Yet, here you are, trying to stop my plans and win back Kyousuke."
        Char "And since I have melted butter in my hair currently, I'd say you succeeded."
        Char "Actually,  I'm kind of a fan, it makes my hair feel a lot smoother!"
        Char "There's a cafe two blocks down the street, go there and be merry."
        Kyou "You could come with us, Charlotte."
        Char "Ohhoho! I appreciate the gesture, but I'm not sure I'd fit the mood. Besides, I got to wash this potion off, and start looking into a new assistant"
        Kan "Um, I made this sweater for Kyousuke, but you should have it instead. You shouldn't walk home covered in that icky, paint like goo."
        Kan "It says 'cool dude', but just ignore that."
        Char " It's so sweet you think Kyousuke's cool, Kanna. But I think this sweater fits me better."
        Char "WAHAHAHA!"
        Char "Well, I bid you two {i}adieu{/i}."
        Kan "Bye, Charlotte."
        Kyou "Bye!"

        Kyou "I don't really get what's happening."
        Kan "Kyousuke, I have something to tell you."
        Kyou "What's up?"
        Kan " Kyousuke I..."
        Kan "I think that..."
        Kan " You're really..."
        Kan "..."
        Kan "I, uh, would like to drink some hot chocolate with you."
        Kyou "Well, uh, sure! That sounds nice."
        Kan "Do you wanna go to the place Charlotte mentioned?"
        Kyou "Absolutely, I'm so hungry."
        Kyou "Let's go!"

        #Cut to Ringo and Youko
        Rin "Welp, that's that, I suppose."
        Rin "Any thoughts, Youko?"
        Youk "Well played, Mr.Fortune."

        #SFX Youko disappears into a poof of purple smoke/sparks.

        Rin "Another wish granted."
        Rin "The last wish granted, huh."

        #ART the screen slowly begins to fade into white.
        # SFX something angelic and subtle.

        Rin "What's happening?"
        Rin "My body is glowing."
        Rin "This feels amazing!"
        Rin "It's finally time! Oh baby I've been waiting for this!"
        Rin "Next stop is paradise!"
        Rin "Thank you, Kanna."

        #End
    "What was I supposed to do again? Better ask Charlotte.":
        #Choice: ""What was I supposed to do again? Better ask Charlotte.""
        #Kanna bad end.

        Kyou "Hey, uh, what am I supposed to do again?"
        Char "Kyousuke! You place the potion, then pour the saliva into it!"
        Kyou "But which one do I do first again?"
        Kan "Kyousuke! Wait!"
        Kyou "What the? Kanna?"
        Kyou "WOOAH."

        "Kyousuke falls over, launching the potion into the air. The potion crashes back down, landing and spilling all over Kyousuke."
        #SFX of Kyousuke being splashed.

        Kan "Kyousuke! Are you alright?"
        Char"Stop, drop, and roll Kyousuke!"
        Kyou "Oooof."
        Kyou "Hey, this stuff doesn't smell too bad."
        Char "How strange... The potion should have turned Kyousuke into fine bolognese sauce."
        Char "I guess I forgot the most important ingredient."
        Kan "Love?"
        Char "Nope! Sulfur!"
        Char "Good thing I forgot it this time, I suppose."
        Char "WAHAHAHA!"
        Kan "I'm so sorry, Kyousuke."
        Kyou "It's alright, Kanna, why are you here anyway?"
        Kan "I..."
        Char "She's here to stop us from cursing the shrine!"
        Char "Well met, fair Kanna."
        Char "Gotta say, when I first met you, I didn't think you were capable of this sort of chicanery."
        Kan "Well, that's kind of true, I'm here to-"
        Char "Now, Kyousuke, we must get you to my domicile so I can give you the antidote!"
        Char "Otherwise your skin will turn purple... in about ten minutes."
        Kyou "What? I don't wanna be purple."
        Char "It's not so bad. I trained with the 'purple extraterrestrial heart and soul kinda dull, never full' ninjas a couple centuries ago."
        Kyou "The what?"
        Char "The purple extraterrestri-"
        Kan "Purple alien ninjas? I thought you trained with monks?"
        Char "Purple alien ninjas who played amazing jazz tunes, I miss them everyday. "
        Char "And remember, someone who has lived as long as me has trained with pretty much everyone."
        Char "They were all very nice... and purple."
        Kyou "As much as I love the non sequitur; I really, really don't want to be purple. It's like, my sixth least favorite color."
        Char " Well then, let's head to my extravagant home."
        Kan "W-w-wait! Kyousuke you can't go with Charlotte."
        Kan " I, I, I have something to tell you."
        Kyou "What is it Kanna?"
        Char "Make it quick! I can already see it tinting his skin."
        Kan "I..."
        Kan"..."
        Kan "I can't tell you like this."
        Kan "Nevermid, you guys gotta go."
        Kan "Here, I brought a sweater for you, Kyousuke."
        Kan "It says 'cool dude' on it."
        Kyou "Oh, thanks, Kanna! Why did you bring me a sweater?"
        Kan"J...just don't worry about it."
        Kyou "Alright! I won't!"
        Char "Are you sure you don't wish to be purple? Like I said, I know a certain group of ninjas that would take you in."
        Kyou "No way! Let's go fix this Charlotte."
        Kyou "Bye Kanna!"
        Kan " Bye..."
        Kan "...Kyousuke."

        #Cut to Ringo and Youko floating by the shrine.

        Youk "Well... that was... something."
        Rin "That might have been the stupidest conclusion I've ever seen."
        Youk "You're aware that Kyousuke going to Charlotte's house means I've won, correct?"
        Rin "Well, that's it, I guess. My perfect wish granting track record is gone, reduced to ashes in front of my eyes."
        Youk "Purple ashes."
        Rin "Oh, get bent!"
        Youk "I won't mess with your shrine anymore, Mr.Fortune, so you're free to start granting  your next wish."
        Rin "Yeah, thanks, I guess."
        Rin "What about Kanna, though?"
        Youk "This is a cut throat business, you shouldn't grow so attached to your clients."
        Youk "But worry not, in a week she'll just be one more client in the millionths you served."
        Rin "I guess..."
        Youk "Take care, Mr.Fortune."
        Youk "I'm sure our paths will cross again."

        #SFX Youko disappears into a poof of purple smoke/sparks.

        "I drift over to Kanna, who's looking up into the night sky."

        Rin " Soooooo, that didn't exactly go as planned, huh?"
        Kan "..."
        Rin "You alright, kid?"
        Kan " I'm just waiting to fall off my bed."
        Rin " Huh?"
        Kan "This dream has been pretty crazy, but I don't think I like it anymore."
        Rin " Kid, it's not..."
        Rin "..."
        Rin " I'm sorry Kanna."
        Kan " It's alright, Mr. Bear."
        Kan "I always wake up from my dreams after I fall out of bed."

        #ART the screen slowly begins to fade into white(or black?).
        #End
