label kannadate:
    # Update the day shown on the upper corner... to nothing!
    $ game_day = ""

    #Note in the locker (Meet me at the rooftop or meet me at the school’s entrance?)

    Kan "Oh my god, Kyousuke! I can't believe you picked me!"
    Kan "I've liked you ever since the first day we met!"
    Kyou "Huh, really? When was that?"
    Kan "I'll never forget that day..."
    Kan "I was chased by a bunch of dogs... and I accidentally ran into a corner without even knowing."
    Rin "(How the hell did you piss off a pack of dogs? Why were you bugging them in the first place?)"
    Kan "I thought I was going to die that day, but then you came to my rescue!"
    Kyou "Actually, I was just passing by and then the dogs started chasing me..."
    Kan "On that day, I knew... I knew that you were the one!"
    Kan "The one who will take me away from this horrible world called 'reality!'"
    Kan "Yes! You! My Kyousuke! My-"
    Rin "(Can you just get to the point already?!)"
    Kyou "I don't know what a 'reality' is, but I'm super excited to go somewhere with you Kanna!"
    Kyou "But I feel like I've been running into you alot lately. It's almost like someone is forcing us to talk with each other, huh?"
    Kyou "You think it's a ghost? Oh no, what if a ghost is making us go out on a date! Would you still want to go if we get haunted?"
    Kan "....."
    Kan "Hah... hah..."
    Kyou "Is that a yes?"
    Kan "Yessssssssssssssss!!!! Yesssssssssssss!!!"
    Kyou "Okay! Say... I bought a couple of amusement park tickets for my dad and me, but he had to change his shifts with someone else."
    Kyou "Want to go with me?"
    Kan "Yes! Anywhere you want, Kyousuke!"
    "Kanna jumps with all the excitement. As she gleefully ran towards Kyousuke to swipe the ticket from his hand."
    Kan "......"
    Kyou "'Kay. Uh... this saturday at 1:00 pm? We should meet at the entrance!"
    Kan "I'll be there at daybreak!!"
    Kyou "Alright!"
    Kyou "See you then."
    # CODE Hide Kyousuke's sprite
    # SFX Footsteps walking away?
    #"Kyousuke walks away... "
    "Wait... if Kanna is going out with Kyousuke, does that mean I'm done?!"
    "???" "Hmph, is that what you think?"
    Rin "*Gasp!*"
    Rin "That voice!"
    Youk "Missed me, Mr. Fortune?"
    Rin "Were you eavesdropping?"
    Youko "Mayhap."
    "He opened his fan and lightly waved it around himself."
    Rin "I'm not letting you sabotage my chances!"
    Rin "Just one more... and I'll be able to go back!"
    Youko "Hmph! Why go back when your form is such a child pleaser?"
    Youko "Your fluffy self would go well in someone's teddy bear collection!"
    Rin "Grrr!!!!"
    "(This guy is really at my nerves!)"
    Youko "This Saturday at 1 pm. Don't be late, oh fluffy one."
    Rin "Dammit,  I had Kanna's fridge to rummage through!"
    Rin "Fine! Challenge accepted!"
    Rin "I will succeed! I have to!"

    #Date time
    "**Date Time"
    Rin "*Yawn!*"
    Rin "Why did we have to show up 2 hours early?!"
    Kan "Kyousuke~ Kyousuke~ We're going on a date~"
    Rin "Kanna! I'm thirsty! I'm hungry! I'm nauseous!I think I'm gonna hurl!"
    Kan "Kyousuke~ Kyousuke~ We're going on a date~"
    Rin "Nope, no response..."
    Rin "*Yawn...*"
    "(What's worse is that I didn't get to sleep much with her throwing clothes everywhere trying to decide what to wear to that date!)"
    Rin "*Sigh* I just hope everything goes well..."
    Kan "Kyousuke!!!"
    Rin "Oh shoot, gotta hide!"
    Kyou "Hey! You're here already?"
    Kan "Of course I am! Why would I miss the best day ever?!"
    Kan "Come on! Let's go in!"
    #Game Booth Scene
    "???" "Ah! You two, come closer!"
    "???" "Are you two, perhaps, a couple?"
    Kan "Y-"
    Kyousuke "I think so?"
    Rin "..."
    Rin "(Have I seen him before?)"
    "???" "Hahaha! You'll have no doubts after this game, I assure you!"
    Rin "(No way... Is that...?!)"
    Kyou "How much to play?"
    Youk  "Absolutely free! Not a single cent."
    Kan "Really?!"
    Kyou "Cool! What do we have to do?"
    Youko  "Simple! Just use the darts provided to hit as many balloons as possible!"
    Youko "If you hit three, you'll get this very special prize!"
    Rin "(What the-?!)"
    Kan "Doesn't it look like me?"
    Kyou "Sounds easy to me!"
    Rin "(I got a bad feeling about this...)"
    Kyou "One!"
    Kyou "Two!"
    Kyou "Haha! Piece of cake. No wonder it's free."
    Rin "I have to stop this!"
    menu:
        "Move dart to the left":
            "math here"
        "Move dart to the right":
            "math here"
        "Move dart upwards":
            "math here"
        "Move dart downwards":
            "math here"
            ###Repeat x 3
            ####If three balloons are hit.:
    "***If 3 balloons are hit, this will play out:"
    Kyou "Three!"
    Youk "Wonderful! Here's your well-deserved prize!"
    Kyou "What the heck is that?"
    Kan "Why does it look like me?!"
    Youko "Turn it's head, It'll talk to you!"
    Kyou "Okay..."
    "*Turns!*"
    "Kanna (Doll)" "Ah~ Kyousuke! I love you, I love you, I love you!"
    "Kanna (Doll)" "I'm so happy I took  his half-eaten yakisoba bread when he wasn't looking! {i}Kyaaaa !{/i} It tasted like Kyousuke~"
    Kyou "What?! You took my yakisoba bread and ate it?!"
    Kan "What? No! I didn't take your-"
    "Kan (doll)" "Did I mention that I took one of Kyousuke's toothbrushes the other day?"
    "Kan (doll)" "I started brushing much more frequently, oh yes I did!"
    Kyou "I thought my mom threw away my toothbrush?!"
    Kyou "Wait... You know where I live?!"
    Kan "Kyousuke! You're attracting too much attention!"
    Kyou "You've been stalking me this whole time?!"
    Kyou "Sorry Kanna, I have a strict no stalkers policy."
    Kyou "I'm outta here!"
    Kan "No, Kyousuke... please..."
    #Heartbroken ending.
    "***If dart does not hit the third balloon:"
    Kyou "Dang it, so close!"
    Kyou "I swear the darts are moving on their own!"
    Kan "Maybe you're just imagining things!"
    Kan "Kyousuke! Would you like to move to the haunted house?"
    Kan "Come on!"
    Kyou "Don't ghosts live in haunted houses? Wait Kanna!"
    Youko "Hmph. Not bad, oh great fluffy one..."
    Youko "But I'm not done yet..."
    #In Haunted House- Courage or Cowardliness?
    ####The frog idea came from this: https://www.youtube.com/watch?v=_IHRNX4p6lQ
    Kan "Kyaaaa!! Protect me, Kyousuke!"
    Kyou "No! Protect me! They're everywhere!"
    Kan  "Yes, Kyousuke~ I'm so horrified by them!"
    Rin "(She just wants an excuse to hold onto him. But he's actually scared of the stupid paper ghosts.)"
    Rin "(Oh my god, they're made for each other...)"
    Kan "Shall we keep going?"
    "Kero... kero..."
    Kyou "Was that you?"
    Kan "What?"
    "Kero kero!"
    Kan "Wahhhhh!!!"
    "All of a sudden, a bunch of green frogs-like creatures were coming right at us."
    "Kero kero! Kero kero! Kero kero!"
    Kyou "Frogs? What the heck?! Is this a prank?"
    "They ran towards the entrance, but it was tightly shut."
    Kyou "Did they do this on purpose?!"
    Kan "They're getting closer, Kyousuke!"
    "Kero! Kero! Kero! Kero!"
    Kan "No! Don't come any closer!"
    Rin "(Oh no! I need to get one of them to do something!)"
    menu:
        Rin "(Who's the bravest of these two?!"
        "Kanna":
            "*****If choose Kyousuke:"
            Rin "Kyousuke! Man up! You got to help your date!"
            Kyou "Ah..."
            "Kero! Kero! Kero! Kero!"
            Kyou "Ahhhhhhhhhhhh!!!"
            Rin "You idiot! Where are you running to?!"
            Kan "Kyousuke, wait!"
            Kan "Oh no, I can't get out!"
            Rin "Crap, I can't either?!"
            Kan "Kyaaaaaaaaaaaa!!!"
            "***Bad End (Kero? Kero?)"
        "Kyousuke":
            "*****If chose Kanna:"
            Rin "Kanna! Can you hear me?"
            Kan "Y-yeah I can hear you!"
            Rin "You want to help your Kyousuke, right?!"
            Kan "Y-yes, I do! But I don't know how!"
            Rin "Look over there! There's another path you can take!"
            Rin "If you really love Kyousuke, then save him from this disaster already!"
            Kyou "Is that my guardian angel? Have you come to save us?"
            Kan  "This way, Kyousuke!"
            Rin "Kanna! Move to your..."

            "***Text based mini-game- Timed choices (Players use their instincts!):"
            menu:
                "Left!":
                    "***Code does something"

                "Right!":
                    "***Code does something"
                ###Repeat x3
            "***If failed:"
            Kan "A dead end!"
            Rin "Crap! We should have gone the other way!"
            Kan "Kyaaaaaaaaaaaa!!!"
            "# Bad End (Kero? Kero?)"
            "***If success:"
            Kyou "Oh no! It's a dead end!"
            Kan "Shoot!"
            "Kero! Kero! Kero! Kero!"
            Kan "There's a window there!"
            Rin "Can you guys break through?"
            Kan "Sorry Kyousuke!"
            Rin "woah, your parents really are feeding you dumbbells!!!"
            Kan "Ready?!"
            Kyou "No I'm not- WAHHHHHHHHH!!!!!!"
            #SFX Glass shattering
            "*Crash!*"
            "Kanna throws Kyousuke out of the window, and follows suit with surprising agility."
            "Of course I joined in too! It was the easiest way out of there!"
            "..................."
            "After that, Kanna and Kyousuke were kicked out for damaging property..."
            "It looks like it can't be helped now. They'd been sitting there for five minutes and no one had said a word yet."
            "Even Kyousuke has been rubbing his head for a while."
            Rin "Psst! Kanna!"
            Kan "What the-?! Is that an ice pack?"
            Rin "Yup. I trust you know what to do."
            Kan "..."
            "Kanna's shaking hands went towards Kyousuke's head..."
            Kan "S-s-"
            #HarukaNami here, this is the part that I just wrote last night. This is a VERY rough draft, but it's almost done~
            Kyou "Ow."
            Kan "Sorry! Does it hurt?"
            Kyou "Of course it does! You threw me out of the window!"
            Kyou "But you did save my butt though. With your freaky crazy super strength."
            Kyou "Thanks for saving me!"
            Kan "....."
            Kan "Oh my god... is Kyousuke saying thank you to me?"
            ###*Boom* cartoon shooting 'sound effect?' OR the VA can make a cute noise like this in the reference XD.
            ###https://www.youtube.com/watch?v=v8cOqzku9zA
            Kyou "Seriously though, were those frogs some kind of joke?"
            Kyou "It wasn't a very funny one, frogs are the second scariest thing on the planet."
            Kan "What's the first?"
            Kyou "Purple frogs. I really don't like the color purple...or frogs."
            Kan "Huh, little weird, but that's alright. I'm scared of spiders."
            Kyou "As long as they aren't purple, I don't mind spiders too much."
            Kan "So, Kyousuke it's starting to get late..."
            Kyou "Yeah, I promised my mom that I will be home by dinner."
            ###If the date was a failure:
            Kan "I had a lot of fun today!"
            Kyou "I didn't..."
            Kan "!"
            Rin "(Oh no...)"
            Kyou "I want to be honest with you. You're a really fun girl Kanna, and I enjoyed spending time with you."
            Kyou "But those frogs were way too much man. If I keep hanging out with you, I'll get flashbacks of being trapped in the haunted house."
            Kyou "Here, take some yen for a taxi."
            Kyou "See ya."
            Kan "Wait what?  Kyousuke No! Come back!"
            "Kyousuke walks away quickly."
            Kan "................."
            Rin ".................."
            Rin "No..."
            Rin "Did we..... fail...."
            Rin "Oh no! Am I being sucked back in the shrine?!"
            Rin "Kanna!"
            Kan "................."
            Rin "At least make another wish! Wish for another guy to like you or something!"
            Rin "Make another wish! Please, I'm begging you!"
            Rin "Kannaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa!!!!!"
            Youk "That's too bad..."
            Youk "I suppose a lifetime stuck in the shrine is a fitting end for the fluffy one?"
            Youk "Ehehehehahaha!"
            "BAD END"

            ###If the date was a success:
            Kan "I had a lot of fun today! Did you, Kyousuke?!"
            Kyou "Huh? Oh, yeah..."
            Rin "(Why is he scratching the back of his head all the sudden?That's unusual...)"
            Kan "Kyousuke... are you okay?"
            Kyou "Huh? Yeah, I'm fine..."
            Kyou "It's just that... there's this school dance coming up soon and..."
            Kan "Are you asking me to go with you?!"
            Kyou "Uhh... yeah. If that's alright. I don't really have a ring or anything to give you though."
            Kyou "Or is it flowers? How does asking people out work?"
            Rin "(Wow... this guy really is hopeless.)"
            Kan "Oh, Kyousuke,you have no idea how HAPPY this makes me!"
            Kan "{i}Cries{/i}"
            Kan "Thank you so much!"
            Kyou "Oh, don't cry..."
            Kyou "Here!"
            #CG? Kyousuke kissing Kanna's forehead to make her stop crying.
            Kyou "Let me take you home!"
            Kan "{i}Sniff Sniff{/i}"
            Kan "It's like a dream come true..."
            Kan "Thank you god for giving me my Kyousuke!"
            Rin "Hey, what about me?"
            Rin "Oh!"
            Rin "My body is glowing?"
            scene black with fade
            #End
return
