#ART BG mall interior

Kyou "Geez, how long is she gonna make me wait?"
Kyou "Do you know how long she's gonna take, Mr. Guardian angel?"
Rin "{i}sigh{/i} I don't know man, maybe she overslept."
Rin "Nah! Actually, she probably forgot about you and found some other guy to boss around."
Kyou "No way she would do that!  Anyways, what's wrong, I thought you wanted me to find a girlfriend?"
Rin "I uh...I'm just restless because... I'm so close to getting you a girlfriend! Once this date goes good, it'll be mission accomplished!"
Kyou "That's great! We make a pretty good team don't we?"
Rin "We sure do kiddo."

Rin "(Gah, I can't stand this kid. I still don't get what Kanna sees in him. )"
Rin "(I wouldn't even be in this mess if Kanna didn't do that stupid letter thing.)"
# VOICE In the following line, Ringo is mocking Kanna, so the VA voice should change to a mocking tone or try to sound like Kanna.
Rin "({i}Oh please, Ringo, just let me talk to Kyousuke without you affecting him, I know he'll make the right choice!{/i})"
Rin "(Well, look how that turned out! Thank god I've been stalking Kyousuke since he wrote that letter. Otherwise we would have been in real trouble.)"
Rin "(Now, we're doing things my way, Kanna! You had your chance.)"

# Enter Maya

Maya "Kyousuke! Sorry, did you wait too long?"
Kyou "Nope, just got here. Everything's all right? You're always so early to everything, I'm surprised I got here first."
Maya "Yeah, my alarm didn't go off this morning. I'm sure I set it right when I went to bed, It's almost like someone turned it off or something."
# ART Maybe replace the following line by a popin of Ringo snickering
Rin "{i}snickers{/i}"
Kyou "Well, what do you think we should do, Maya? It was your idea to come here, after all."
Maya "We'll go shopping first, then get something to eat afterward. Walking around will build up an appetite."
Maya "My favorite store is on the other side of the mall anyway, let's start heading over."
Kyou "Sweet! Let's go!"
Rin "(Alright, I got some time to check in with Kanna before they get there.)"

# Transition
#Same Mall BG, Ringo teleports to a different part of the mall.

#Food Court-

Rin "Ok, I'm back."
Kan "Ringo, what are we doing here? We lost, we should just go hom-"
Rin "Kanna, shut it."
Kan "Hey! That's not ver-"
Rin "Out of the three girls that were fighting for Kyousuke, the one without the spirit got him..."
Rin "Do you know how dumb that is!? Regular teenage girls are like the most boring people on the planet!"
Rin "Erm, except you, of course."
Rin "Kyousuke is gonna see how boring and mean Maya is, then he'll see you here at the food court eating alone and come sit down with you."
Rin "The deal will be sealed, and I'll retire and party until the end of time."
Kan "I told you, I don't want you using any more magic!"
Kan "Kyousuke made a choice and he chose Maya. That's more real than anything me and him have."
Rin "Kanna, it's Maya. Do you really think she's not bossing him around right now? You know how self-centered she is! Do you think he wants his life controlled by her?"
Rin "Well, he might actually really like that... But still, you deserve him much more than Maya does!"
Rin "Maya wants to mount Kyousuke over her fireplace and show him off to her friends, you genuinely like the guy."
Rin "And I think people who genuinely like other people should be together. Don't you agree?"
Kan "..."
Rin "And I'm pretty sure Kyousuke genuinely likes you."
Kan "..."
Kan "Are you gonna use your magic?"
Rin "Don't worry 'bout that."
Kan "Ringo!"
Rin "Do you want to be with him or not?"
Kan "...I do."
Rin "Do you think Kyousuke will be happy with Maya?"
Kan "...Probably not."
Rin "Probably not? Come on, be sure of yourself."
Kan " No, I don't think he'll be happy with her."
Rin "There ya go!  Now just sit tight and look at dumb memes on your phone or get some food or something, let me handle this one."
Kan "I don't know Ringo..."
Rin "Well, if you had a pair as big as Maya's and just asked him out instead of summoning me, we wouldn't be in this mess!"
Kan "Bigger? Mine are way bigger! They're even bigger than you! You're like barely half a foot tall, you dumb bear!"
Rin "That's it! Maybe I should ju... {i}Sigh.{/i} This isn't gonna get us anywhere."
Rin "We're saving Kyousuke from Maya, think of it like that, ok? Will that solve your ethical quandary?"
Kan "...I guess. Maya is kinda mean, and I want Kyousuke to live his own life."
Rin "Alright, now let me handle this, ok?"
Kan "...Ok."

#Clothing store
Kyou "Woah, so that's your secret to how you can get so much done!"
Maya "Yep, pretty amazing, isn't it?"
Kyou "If the world knew about this, everyone's problems would be solved!"
Maya "Violence, hunger, economic disparity, crime, anime, all the issues of the world would be gone. If they used my system."
Kyou "Why don't you tell anyone about this?"
Maya "Kyousuke, if I spent all my time trying to make the world a better place, how could we go clothes shopping together?"
Kyou "Isn't trying to help the world more important than clothes shopping?"
Maya "Think about it like this Kyousuke, we can only make the world better by helping one person at a time, right?"
Kyou "Umm, right!"
Maya "And buying new outfits makes me happy, which means it's helping me. So we can start helping the whole world by doing things for me, make sense?"
Kyou "Huh, good point. Alright, what did you want to ask me before we got side tracked?"
Maya "I'm going to try this outfit on, let me know if you like it."
Kyou "Are you sure?! I don't really know much about girl's clothing."
Maya "Oh, come on, you know plenty. A rising fashionista such as yourself has to know what looks good and what doesn't, right?."
Kyou "Uhhh..."
Maya "Just the other day you came to school with your uniform not fully tucked in and messy looking."
Kyou "I did?"
Maya "You did. You told me all about how you're making a huge anti-establishment statement and how you're not confined by the rules of our school."
Maya "You're such a bad boy, Kyousuke~"
Kyou "I er...that's right! I'm fighting against the system and I know everything about women's clothing!"
Maya "There ya go! Alright, let me go change."
Rin "Oh, give me a break, these two are a pain in the ass! Good thing I was away most of the time…"
"Maya goes into a changing booth"
# CODE small pause (maybe a fade) to simulate the time Maya took to get herself dressed.
Maya "So, how do I look?"

#ART If possible, change Maya's clothes, something fashionable, up to the artist, have fun with #it. If a different costume is not possible, maybe don't show Maya for this scene. It'd be weird to #have her change and come out in the same outfit.
Rin "(Ok, it's showtime. I shouldn't be too blunt otherwise Maya might suspect something's up. Let's see.)"
#Choices for Kyousuke:
# 1) "Really? Is that all you got? Looks kinda bland."
# 2) "Can we hurry up? I'm really hungry."

#Choice: "Really? Is that all you got? Looks kinda bland."

Maya "Oh, you think I just grabbed this outfit by mere chance?  Hmph, looks like I'm going to have to show you I'm more than meets the eye."
"Maya spins around to reveal a gold rainbow necklace which she kept hidden. "
Maya "Now, what do you think? You regret thinking I look bland now, don't you?"
Kyou "Wow! Maya, that looks amazing! I didn't even see you put that on!"
Maya "Makes the outfit look so much better, huh? Nice try, Kyousuke, but you should know by now that I'm always one step ahead."
Maya "Now, come. As punishment for not believing in my fashion choices, I think you should pay for this outfit."
Kyou "What? Wait a minute I thought you said I was a rising fashion person or something. Why would I have to pay?"
Maya "Well, you are, Kyousuke! But I am part of the fashion club, so I am a fashionista in training too."
Maya "Normally, you are a much better judge of these things, but I guess today you made a mistake and people have to pay for mistakes, right? Otherwise they'll never get better."
Kyou "...I guess that makes sense. And if people never get better, then the world won't get better either, right?"
Maya "Exactly! Now let's go pay for these clothes and get something to eat."
Kyou "Yes Ma'am!"
Rin "{i}Gah!{/i} What a conceited girl! Kyousuke, have some backbone, man!"

#Choice: "Can we hurry up? I'm really hungry.""

Maya "Now, come on, Kyousuke, don't talk like that."
Kyou "But I'm really hungry."
Maya "Yes and we'll eat after this. Don't you have anything to say about my outfit?"
"Maya spins around in a circle."
Kyou "It uh...looks nice, I guess?"
Maya "That's all? Really? Do you really think you'll make it in the fashion industry with 'looks nice, I guess?'"
"A glowing choice pops up in front of Kyousuke again"
Rin "Sorry, bud, but I gotta keep up the charade."
Kyou "Sorry, Maya, can't think on an empty stomach. We should go eat."
Maya "...Fine, whatever. Let me- actually, I think there's a lesson to be learned here, Kyousuke."
Kyou "A lesson? What do you mean?"
Maya "You can't think straight because you're hungry? That's no good, Kyousuke."
Maya "If you're going to learn to think like a fashion designer, you need to be able think without letting bodily pleasures get in the way."
Maya "And the first step to learning to think without distractions, is to get rid of material possessions. What do you have on you?"
Kyou "Uhh...phone, keys, my wallet. That's it really."
Maya "Well, you can't be without your keys or phone, that's too problematic. How about you unload some money from your wallet?"
Maya "I'm sure that will make you think more clearly! Then you can tell me how good I look in this outfit and  pay for it."
Maya "It's a win-win for both of us, right? "
Kyou "..."
Maya "Sound good, Kyousuke?"
Kyou "I'll be real with you, Maya, I have no idea what you just said. I've been thinking about quesadillas this whole time."
Maya "Just...whatever. Let me put these clothes back and we can go."

Rin "My god, this girl is evil! Is she like this all the time when it's just the two of them?"
Rin "I guess it's a good thing he's thick as a brick for once."

#Food Court

Maya "Alright, be frank with me, Kyousuke, what do you want to eat?"
Kyou "How can I be Frank if I'm Kyousuke?"
Maya "{i}Deep sigh.{/i} Alright, be honest with me, Kyousuke, what do you want to eat? "
Kyou "Hmm, how about tacos?"
Maya "Nope."
Kyou "Uh, pizza?"
Maya "Try again."
Kyou "Sushi?"
Maya "Oh, you want sushi? So do I! Let's go!"
"They both order their food and sit down in the food court."
Kyou "And that's how I learned to breathe through my nose."
Maya "Oh my god, Kyousuke, that's amazing! Most people go their whole lives without learning that!"
Kyou "I know! I'm also learning how to listen to my heartbeat. I always forget how to do it, though."
Maya "You take your finger and push on your neck gently and then you can feel your heartbeat."
Kyou "Oh yeah, that's right, let me try it- GAH ACK."
Maya "Woah, woah, Kyousuke, not that hard; you don't want to choke yourself. Gently, like this"
"Maya pushes gently on Kyousuke's neck."
Maya "See? That gentle."
Kyou "{i}Huff huff.{/i} Oh, that makes a lot more sense."
Maya "Ok, Kyousuke, let me ask you something."
Maya "Would you like to do more stuff like this? Go on more dates?"
Kyou "Well..."
Rin "(Ok, this is where I come in.)"
Rin "(Kanna is sitting at a table behind them. Maybe if I can get him to notice Kanna, he'll want to talk with her. I should find something to make him stand up.)"
Rin "(Or I can make some excuse as to why he can't go anymore. And try to end any future dates.)"
#Choices for Kyousuke:
# 1) "One sec, I gotta use the bathroom."
# 2) "I don't have the time to go on more dates."

#Choice:"I don't have the time to go on more dates."
#Maya Ending

Maya "Kyousuke, don't you remember what we were talking about earlier? I have perfected time management."
Maya "We can work together to make sure we can keep dating, that is how relationships work, remember?"
Kyou "That's right! We had that talk so long ago, I guess I already forgot."
Maya "Yes, ten minutes is a long time. Here, tell you what, what if I managed all your time?"
Maya "I can plan your days - heck, even your whole life - so that you won't have to worry about missing out on anything and still have  time for your new girlfriend."
Maya "Just let me control you- er, control your time and you'll have more time to focus on all your projects!"
Kyou "Projects? I was working on something?"
Maya "Yeah! You were telling me how you wanted to run in the student council election, remember?"
Kyou "I do?"
Maya "Yeah, you were telling me how you wanted to make all sorts of changes to the school, starting with the dress code, don't you remember? "
Kyou "Umm, I do now! That's right, I think we should be able to dress how we want...right?"
Maya "That's right! I think you mentioned having the girls of the school pick out uniforms the guys wear, but the girls are free to dress how they want."
Maya "Or something like that, let's not worry about specifics right now. Just let me take care of you, Kyousuke, and everything will work out~"
Kyou "I'm glad we're dating now, Maya, it feels like a dream."
Maya "It feels like a dream to me too, Kyousuke~"

Rin "(Oof, that went from zero to a hundred real fast! I got to report back to Kanna to see what we do next.)"
"Ringo floats over to Kanna's table."
Rin "What the, she ain't here? Where did she go? I don't feel her presence anywhere in the mall."
Rin "What the? A note?"
"Ringo picks up the note left on the table."
Rin "'{i}Kyousuke should be with the person that makes him the most happy. And I know it's not me.{i}"
Rin "'{i}I know you said that Maya is a bad person that shouldn't be with Kyousuke, but they've been friends for so long. Seeing them have fun together at the table across from me,  I think maybe we're wrong about this one.{i}."
Rin "'{i} Kyousuke is happy with her, and I guess that's enough for me.  Thanks for trying Ringo, good luck with your next wish and your retirement.{/i}'"
Rin "Wait? Nonononono, there's still time! Kanna, you idiot! You told me you didn't think Kyousuke was a good fit for Maya!"
Rin "God, why are teenagers so wishy washy with their feelings!"

Maya "Do you want to head back to my place? My mom's making homemade ice tea, it's some seriously good stuff."
Kyou "G-going to a girls house? Can I do that?"
Maya "You've been to my house before when we walked your dog remember? Come on, let's go."

Rin "Nononono, they can't leave until Kanna comes back!"
Rin "I can't give up. I... I..."
"Ringo looks back down at the note."
# The sigh should be deep and sorrowful.
Rin "{i}Siiiiggggghhhhh.{/i} Imagine that, a week of work gone for one wish. The millionth wish..."
Rin "I could have completed like fifty wishes instead of this one. I guess I'm not as powerful as I thought..."
Rin "Doing everything right, only to freakin' bungle it at the end."
Rin "{i}Sigh.{/i} I guess, uh... I guess I better wait for the next person to make a wish on the shrine."
Rin "I'm sorry Kanna, I really am."
#Fade to black.
#End


#Choices for Kyousuke:
#"One sec, I gotta use the bathroom."

#Kanna Ending (Maya variant)

Maya "Well, alright, just hurry back quickl-"
Kyou "Don't worry, I won't be lo- Hey, is that Kanna over there?"
Maya "What? No, of course not. Then again, all average girls look the same..."
Kyou "No, I think that is Kanna! We should go say hi!"
Maya "Kyousuke, no, come back here right now!"
"Kyousuke stands up and walks over to Kanna's table. "
Kan "K-K-Kyousuke, hi! Didn't expect to s-see you here!"
Kyou "Hi, Kanna! How are you? Are you here all by yourself?"
Kan "W-well I-"
Maya "Kanna! What do you think you're doing here? Spying on us?"
Kan "N-no! I just really love the tacos here. The fish tacos especially, they are pretty dang good."
Kyou "I know, right! I think my favorite are th-"
Maya "Seriously? What a lame excuse. You're trying to mess with our date today, aren't you?"
Kan "N-no! Seriously, I'm just here for the food! And the uh...atmosphere of the place."
Maya "That's a load of bull and you know it.  You don't have the guts to come here on your own and I know that Kanna. Who put you up to this? Charlotte?"
Kan "..."
Kyou "Hey, come on now, Maya, she's just trying to eat a delicious fish taco. You don't have to be so mean."
Maya "You're telling me all three of us girls agree to the terms that she made herself -  to let you, Kyousuke, deliver a letter and go from there - and she can't even follow her own rules? "
Maya "You're telling me it's just a happy happenstance that you're here on the day we decided to go on a date? Really? Is that what you're telling me right now, Kanna?"
Maya "You pulled some kind of magical mambo jumbo from your butt to deal with Charlotte, and now it's my turn right?"
Maya "Because you can't handle the fact Kyousuke chose someone who wasn't you, even though I won him fair and square. He's mine."
Maya "So now you're here to cheat your way in? Real mature. That must be why I never see you with anybody else. Do you even have friends? You know, no one likes a cheat, Kanna."
Maya "I'm not gonna sit here and pretend you're not up to something to ruin our day. You should just go home, Kanna, no one wants you here anyway."
Kan "..."
Kan "You won him fair and square? Do you mean that? That's what you just said right?"
Maya "What? Yes, that's what I just said, try listening next time."
Kan "You don't win love Maya. Kyousuke isn't an object, he's a person - an amazing person who loves everyone with all his heart. Love is not something you force someone to do."
Kan "Kyousuke should be with someone he really loves, and that person should love him back. And I don't think that person is you, Maya."
Maya "Excuse me? Kyousuke chose {b}ME{/b} in the dumb letter, I literally just said that. Kyousuke is obedient, he knows he had to pick me."
Maya "Just look at me! How could he even think to pick between your frumpy ass or Charlotte's messed up head? I'm the only real option."
Maya "Besides I TOLD him to pick me at the end of the day. And he always listens to me, because I'm his childhood friend, he's obligated to do anything I say."
Maya "So, like I already said, why don't you stuff your fat face with your tacos, and waddle on home? At least have some dignity in losing."
Kyou "..."
Kyou "Actually, Maya, I think you should go home. That's really mean and I think you need to cool off."
Maya "What!?"
Kyou "She's just here eating a taco, and you blew up on her. I don't think she's the bad guy here."
Kan "..."
Maya "..."
Maya "Well, fine! Whatever! Fall for her dumb tricks then, Kyousuke. See how far you make it."
"Maya stomps off in the opposite direction. "
Kan "{i}Sniff.  Sniff. Waaaaaaaaa...{/i}"
Kyou "Hey, it's alright."
Kan "B-b-but everything she said was true! Kyousuke, I've bee-"
Kyou "Hey, I don't care. And I don't think you're fat at all."
Kan "N-no, not t-that. You s-should really know the t-truth."
Kyou "The only truth I see and care about here is that you got one more taco left. You gonna eat that?"
Kan "N-no. You can have it. I guess."
Kyou "Sweetness! You know, eating something always clears my head and makes me feel better."
Kyou "But it looks like you're all out of food. You still hungry?"
Kan "Y-you just ate my last taco."
Kyou "So, we need to go something else to eat, right? You like pizza?"
Kan "...Yea."
Kyou "Well, let's go! I'm sure that'll cheer you up Kanna!"
Kan "But Kyousuke, I'm no better than Maya, I've been tricking you this who-"
Kyou "Hey now, if we ain't talking about pizza, it's not important."
Kyou "Besides, I feel like Maya might have been the one messing with me this whole time, though I'm not sure how."
Kyou "She doesn't even like pizza or tacos... I mean, come on, that's not human."
Kan "But..."
Kyou "No more buts, we've had enough crying and yelling today, let's just hang out for a while, ok?"
Kan "I...alright. {i}Sniff.{/i} Let's go Kyousuke."

Rin "It's funny how somethings work out. That arrogant girl dug her own grave."
Rin "And gave my dumb girl a chance to just let things happen, I guess. Maybe Kyousuke isn't as stupid as I thought."
Rin "Wait, does that moron even like Kanna or is he just hungry?"
Rin "Doesn't matter, that's another wish granted!"
Rin "My last wish, huh."

#ART the screen slowly begins to fade into white.
# SFX something angelic and subtle.

Rin "What's happening?"
Rin "My body is glowing."
Rin "This feels amazing!"
Rin "It's finally time! Oh baby, I've been waiting for this!"
Rin "Next stop is paradise!"
Rin "Thank you, Kanna."

#End
