label mayadate:

    # Update the day shown on the upper corner... to nothing!
    $ game_day = ""

    #ART BG Festival

    Kyou "Geez, how long is she gonna make me wait?"
    Kyou "Do you know how long she's gonna take, Mr. Guardian angel?"
    Rin "{i}sigh{/i} I don't know man, maybe she overslept."
    Kyou " Overslept? It's night time. Plus we've been excited for Kumamatsuri all week. There's no way she would miss it."
    Rin "She probably forgot about you and found some other guy to boss around."
    Kyou "No way she would do that!  And why are you grump? I thought you wanted me to find a girlfriend?"
    Rin "I uh...I'm just restless because... I'm so close to getting you a girlfriend! Once this date goes good, it'll be mission accomplished!"
    Kyou "That's great! We make a pretty good team don't we?"
    Rin "We sure do kiddo."

    Rin "(What on earth does Kanna see in this guy. )"
    Rin "(I wouldn't even be in this mess if Kanna didn't do that stupid letter thing.)"
    # VOICE In the following line, Ringo is mocking Kanna, so the VA voice should change to a mocking tone or try to sound like Kanna.
    Rin "({i}Oh please, Ringo, just let me talk to Kyousuke without you affecting him, I know he'll make the right choice!{/i})"
    Rin "(Well, look how that turned out! Thank god I've been stalking Kyousuke since he wrote that letter. Otherwise we would have been in real trouble.)"
    Rin "(Now, we're doing things my way. You had your chance Kanna!)"

    # Enter Maya

    Maya "Kyousuke! Sorry, did you wait too long?"
    Kyou "Nope, just got here. Everything's all right? You're always so early to everything, I'm surprised I got here first."
    Maya "I just couldn't find any clothes to wear! Somehow all of my clothes except for my school uniform were in the wash."
    Kyou "That's a lot of laundry. Did you really have that much dirty clothes?"
    Maya "No, of course not!  think my mom wanted to do my laundry to help out, but I don't know why she throw my clean clothes in the wash too."
    Maya "If it wasn't mom, I don't know who else could have done it."
    Maya "So embarrassing coming to Kumamatsuri in a school uniform."
    # ART Maybe replace the following line by a popin of Ringo snickering
    Rin "{i}snickers{/i}"

    Kyou "I think it's alright! I came in my uniform too after all. It's like we're matching!"
    Maya "That is fun Kyousuke, but I'm not going to walk around the biggest festival of the year in a uniform."
    Maya "I know there's some stores around here somewhere, let's go shopping first and then we'll go look at all the stands."
    Kyou "Aww, but I'm starving!"
    Maya "Shopping first, then get something to eat afterward. Trying yukatas on will build up an appetite anyway."
    Kyou "No food?"
    Maya "Clothes first. Food later."
    Kyou "Good enough! Let's go!"
    Rin "(I better check in with Kanna.)"

    # Transition
    #Same Festival Background , Ringo teleports to a different part of the mall.

    Rin "Ok, I'm back."
    Kan "Ringo, what are we doing here? We lost, we should just go hom-"
    Rin "Kanna, shut it."
    Kan "Hey! That's not ver-"
    Rin "Out of the three girls that were fighting for Kyousuke, the one without the spirit got him..."
    Rin "Do you know how dumb that is!? Regular teenage girls are like the most boring people on the planet!"
    Rin "Erm, except you, of course."
    Rin "Kyousuke is gonna see how boring and mean Maya is, then he'll see you here at the festival all alone and come to you.."
    Rin "The deal will be sealed, no more big dumb bear, and then I  party until the end of time."
    Kan "I told you, I don't want you using any more magic!"
    Kan "Kyousuke made a choice and he chose Maya. That's more real than anything me and him have."
    Rin "Kanna, it's Maya. Do you really think she's not bossing him around right now? You know how self-centered she is! Do you think he wants his life controlled by her?"
    Rin "Well, he might actually really like that... But still, you deserve him much more than Maya does!"
    Rin "Maya wants to mount Kyousuke over her fireplace and show him off to her friends, you genuinely like the guy."
    Rin "And I think people who genuinely like other people should be together. Don't you agree?"
    Kan "..."
    Rin "And I'm pretty sure Kyousuke genuinely likes you."
    Kan "..."
    Kan "Are you gonna use your magic?"
    Rin "Don't worry 'bout that."
    Kan "Ringo!"
    Rin "Do you want to be with him or not?"
    Kan "...I do."
    Rin "Do you think Kyousuke will be happy with Maya?"
    Kan "...Probably not."
    Rin "Probably not? Come on, be sure of yourself."
    Kan " No, I don't think he'll be happy with her."
    Rin "There ya go!  Now just sit tight, hang around the food booths and try to get something good to eat. you're at a festival, act like it! Just enjoy yourself while I handle this one."
    Kan "I don't know Ringo..."
    Rin "Well, if you had a pair as big as Maya's and just asked him out instead of summoning me, we wouldn't be in this mess!"
    Kan "Bigger? Mine are way bigger! They're even bigger than you! You're like barely half a foot tall, you dumb bear!"
    Rin "That's it! Maybe I should ju... {i}Sigh.{/i} This isn't gonna get us anywhere."
    Rin "We're saving Kyousuke from Maya, think of it like that, OK? Will that solve your dumb little ethical quandary?"
    Kan "...I guess. Maya is kinda mean, and I want Kyousuke to live his own life."
    Rin "Alright, now let me handle this, ok?"
    Kan "...Ok."

    #Transition back to Kyousuke and Maya. They are about to enter the clothing store/

    Kyou "Woah, so that's your secret to how you can get so much done all the time!"
    Maya "Yep, pretty amazing, isn't it?"
    Kyou "If the world knew about this, everyone's problems would be solved!"
    Maya "Violence, hunger, economic disparity, crime, anime, all the issues of the world would be gone. If they used my system."
    Kyou "Why don't you tell anyone about this?"
    Maya "Kyousuke, if I spent all my time trying to make the world a better place, how could we go clothes shopping together?"
    Kyou "Isn't trying to help the world more important than clothes shopping?"
    Maya "Think about it like this Kyousuke, we can only make the world better by helping one person at a time, right?"
    Kyou "Umm, right!"
    Maya "And buying new outfits makes me happy, which means it's helping me. So we can start helping the whole world by doing things for me, make sense?"
    Kyou "Huh, good point. Alright, what did you want to ask me before we got side tracked?"
    Maya "I'm going to try this outfit on, let me know if you like it."
    Kyou "I thought we were here to get a yukata?"
    Maya "We are, but there's no harm in trying some other outfits on too, is there?"
    Maya "When else am I going to get your expert fashion advice, Kyousuke?"
    Kyou "Expert? I don't really know much about girl's clothing."
    Maya "Oh, come on, you know plenty. A rising fashionista such as yourself has to know what looks good and what doesn't, right?."
    Kyou "Uhhh..."
    Maya "Just the other day you came to school with your uniform not fully tucked in and messy looking."
    Kyou "I did?"
    Maya "You did. You told me all about how you're making a huge anti-establishment statement and how you're not confined by the rules of our school."
    Maya "You're such a bad boy, Kyousuke~"
    Kyou "I er...that's right! I'm fighting against the system and I know everything about women's clothing!"
    Maya "There ya go! Alright, let me go change."
    Rin "(I'm going to go insane if I have to listen to these two talk for one more second. Good thing I was away most of the time.)"

    # Transition to the Maya trying on clothes CG.
    # CODE small pause (maybe a fade) to simulate the time Maya took to get herself dressed.

    Maya "So, how do I look?"
    Kyou "That's a really weird looking yukata."
    Maya "I already have a yukata picked out, that's a surprise."
    Maya "But other outfits I'll need your professional opinion on."
    Kyou "Oh! Alright!"

    Rin "(Ok, it's showtime. I shouldn't be too blunt otherwise Maya might suspect something's up. Let's see.)"

    #Choices for Kyousuke:
    # 1) "Really? Is that all you got? Looks kinda bland."
    # 2) "Can we hurry up? I'm really hungry."

    #Choice: "Really? Is that all you got? Looks kinda bland."

    Maya "Oh, you think I just grabbed this outfit by mere chance?  Hmph, looks like I'm going to have to show you I'm more than meets the eye."
    "Maya spins around to reveal a gold rainbow necklace which she kept hidden."
    Maya "Now, what do you think? You regret thinking I look bland now, don't you?"
    Kyou "Wow! Maya, you look amazing! I didn't even see you put that on!"
    Maya "Makes the outfit look so much better, huh? Nice try, Kyousuke, but you should know by now that I'm always one step ahead."
    Maya "As punishment for not believing in my fashion choices, I think you should pay for this outfit."
    Kyou "What? Wait a minute I thought you said I was a rising fashion person or something. Why would I have to pay?"
    Maya "Well, you are, Kyousuke! But I am part of the fashion club, so I am a fashionista in training too."
    Maya "Normally, you are a much better judge of these things, but I guess today you made a mistake and people have to pay for mistakes, right? Otherwise they'll never get better."
    Kyou "I guess that makes sense. And if people never get better, then the world won't get better either, right?"
    Maya "Exactly! Now let's go pay for these clothes and get something to eat."
    Maya "I'll go change into the yukata real quick. Remember to pay for that too~."
    Kyou "Yes Ma'am!"
    Rin "({i}Gah!{/i} What a conceited girl! Kyousuke my man, have some backbone!)"

    #Choice: "Can we hurry up? I'm really hungry.""

    Maya "Now, come on, Kyousuke, don't talk like that."
    Kyou "But I'm really hungry."
    Maya "Yes and we'll eat after this. Don't you have anything to say about my outfit?"
    "Maya spins around in a circle."
    Kyou "It uh...looks nice, I guess?"
    Maya "That's all? Really? Do you really think you'll make it in the fashion industry with {i}looks nice, I guess?{/i}"
    "A glowing choice pops up in front of Kyousuke again"
    Rin "(Sorry, bud, but I gotta keep up the charade.)"
    Kyou "Sorry, Maya, can't think on an empty stomach. We should go eat."
    Maya "Fine, whatever. Let me- actually, I think there's a lesson to be learned here, Kyousuke."
    Kyou "A lesson? What do you mean?"
    Maya "You can't think straight because you're hungry? That's no good, Kyousuke."
    Maya "If you're going to learn to think like a fashion designer, you need to be able to think without letting bodily pleasures get in the way."
    Maya "And the first step to learning to think without distractions, is to get rid of material possessions. What do you have on you?"
    Kyou "Uhh...phone, keys, my wallet. That's it really."
    Maya "Well, you can't be without your keys or phone, that's too problematic. How about you unload some money from your wallet?"
    Maya "I'm sure that will make you think more clearly! Then you can tell me how good I look in this outfit and pay for it."
    Maya "It's a win-win for both of us, right? "
    Kyou "..."
    Maya "Sound good, Kyousuke?"
    Kyou "I'll be real with you, Maya, I have no idea what you just said. I've been thinking about gyoza this whole time."
    Maya "Just...whatever. Let me put these clothes back and we can go."
    Kyou "What about the yukata?"
    Maya"Right. I'll go change and pay for that too. Then we'll head to the festival."

    Rin "(My god, this girl is evil! Is she like this all the time when it's just the two of them?)"
    Rin "(I guess it's a good thing he's thick as a brick for once.)"

    #Festival grounds - Getting food

    Maya "Alright, be frank with me, Kyousuke, what do you want to eat?"
    Kyou "How can I be Frank if I'm Kyousuke?"
    Maya "{i}Deep sigh.{/i} Alright, be honest with me, Kyousuke, what do you want to eat?"
    Kyou "Hmm, there's so many stands around here. And everything smells {i}sooooooo gooooodddd{/i}."
    Kyou "Oh! How about dumplings?"
    Maya "Nope."
    Kyou "Uh, sweet potatoes?"
    Maya "Try again."
    Kyou "Taiyaki?"
    Maya "Oh, you want taiyaki? So do I! Let's go!"
    Kyou "Huh. I've never had taiyaki before. But everything around here smells so good, I'm sure it's gonna be good!"
    Maya" It's delicious Kyousuke. I just know you'll love it."

#Transition to them already getting their food.


    Kyou "And that's how I learned to breathe through my nose."
    Maya "Oh my god, Kyousuke, that's amazing! Most people go their whole lives without learning that!"
    Kyou "I know! I'm also learning how to listen to my heartbeat. I always forget how to do it, though."
    Maya "You take your finger and push on your neck gently and then you can feel your heartbeat."
    Kyou "Oh yeah, that's right, let me try it- GAH ACK."
    Maya "Woah, woah, Kyousuke, not that hard; you don't want to choke yourself. Gently, like this"
    "Maya pushes gently on Kyousuke's neck."
    Maya "See? That gentle."
    Kyou "{i}Huff huff.{/i} Oh, that makes a lot more sense."

    Maya "Which taiyaki did you get? Mines got custard cream."
    Kyou "The bean one!"
    Maya "The what one?"
    Kyou "Mines filled with beans!"
    Kyou "Kidney, baked, lima, black, I don't know what kind it comes with, but I know there's beans in this little fish-shaped pancake thingy."
    Maya "I'm pretty sure it's just red bean paste."
    Kyou "That's good. I really didn't want to bite into a pancake filled with baked beans."
    Kyou "..."
    Maya "Well, how is it? Pretty good right?"
#Kyousuke talking while he's eatting
    Kyou "Vury Gomp!"
    Kyou "Can I try a bite of yours? Custard bean sounds like a really interesting filling."
    Maya "It's custard cream. And you can only have a bite of mine if I can have a bite of yours."
    Kyou "Hmmm, you drive a hard bargain Maya. But you got yourself a deal."
    Kyou "…"
    Maya "Yours is really good! Still sweet, but with just the right pinch of saltiness. I like the chunks of red beans."
    Kyou "I think they had the chunks in to get the maximum amount of beanage per bite."
    Kyou "Yours is even better Maya! I kinda like how it's more like a dessert than a snack."
    Maya "Say Kyousuke, you're a man of economic prowess. How about we strike a deal."
    Maya "We open trade between ourselves and exchange our local commodities."
    Kyou "Huh?"
    Maya "Since we like each other's food more, we should swap our substances so we can enjoy them more."
    Kyou "Swap our what now?"
    Maya "My custard cream for your red bean."
    Kyou "Red cream custard bean?"
    Maya "You give me your taiyaki and I'll give you mine."
    Kyou "Gotcha! Yours tastes better anyway."
    Kyou "But is that a fair trade? You ate almost all of your custard one, and I haven't even gotten halfway through mine yet."
    Maya "Well, would you rather have a lot of something you like, or a little bit of something you love?"
    Maya "If life is all about getting the best possible experiences we can, wouldn't it be better to make sure you always try to do things you love?"
    Maya "It may not seem like a fair trade in quantity, but it seems like more than a fair trade in quality, don't you think?"
    Kyou "Hmm, you might be right Maya. Just like how we were talking about making the world a better place one step at a time at the clothes store."
    Maya "Exactly! Pursuing what you love most in life will lead to the most good happening. Which will lead to the world being the best possible place it can be."
    Kyou "And that's a good thing!"
    Maya "But of course!"
    Kyou "Alright your cream bean for my red custard. Here you go!"
    Maya "Pleasure doing business with you, Kyousuke."
    Rin "(She can't let him have anything! Twisting him around for half a fish shaped pancake just because she can. How petty can someone be?)"

    Maya "Ok, Kyousuke, let me ask you something."
    Maya "Would you like to do more stuff like this? Go on more dates?"
    Kyou "Well..."
    Rin "(Ok, this is where I come in.)"
    Rin "(Kanna is sitting at one of the benches behind them. Maybe if I can get him to notice Kanna, he'll want to talk with her. I should find something to make him look around.)"
    Rin "(Or I can make some excuse as to why he can't go anymore. And try to end any future dates.)"
    #Choices for Kyousuke:
    # 1) "One sec, I gotta use the bathroom."
    # 2) "I don't have the time to go on more dates."

    #Choice:"I don't have the time to go on more dates."
    #Maya Ending

    Maya "Kyousuke, don't you remember what we were talking about earlier? I have perfected time management."
    Maya "We can work together to make sure we can keep dating. That is how relationships work, remember?"
    Kyou "That's right! We had that talk so long ago, I guess I already forgot."
    Maya "Yes, a half hour is a long time. Here, tell you what, what if I managed all your time?"
    Maya "I can plan your days - heck, even your whole life - so that you won't have to worry about missing out on anything and still have time for your new girlfriend."
    Maya "Just let me control your time and you'll have more time to focus on all your projects!"
    Kyou "Projects? I was working on something?"
    Maya "Yeah! You were telling me how you wanted to run in the student council election, remember?"
    Kyou "I do?"
    Maya "Yeah, you were telling me how you wanted to make all sorts of changes to the school, starting with the dress code. Don't you remember? "
    Kyou "Umm, I do now! That's right, I think we should be able to dress how we want...right?"
    Maya "That's right! I think you mentioned having the girls of the school pick out uniforms the guys wear, but the girls are free to dress how they want."
    Maya "Or something like that, let's not worry about specifics right now. Just let me take care of you, Kyousuke, and everything will work out~"
    Kyou "I'm glad we're dating now, Maya, it feels like a dream."
    Maya "It feels like a dream to me too."

    Rin "(Oof, that went from zero to a hundred real fast! I got to report back to Kanna to see what we do next.)"
    "Ringo floats over to Kanna's table."
    Rin "What the, she ain't here? Where did she go? I don't feel her presence anywhere in the mall."
    Rin "What the? A note? From Kanna? What is she doing leaving something like this out in the public?"
    Rin "This better be some kind of dumb joke Kanna. I swear to god if you ditched me."

    Rin "{i}Ringo…{/i}"
    Rin "'{i}Kyousuke should be with the person that makes him the most happy. And I know it's not me.{/i}"
    Rin "'{i}I know you said that Maya is a bad person that shouldn't be with Kyousuke, but they've been friends for so long. Seeing them have fun together at the table across from me,  I think maybe we're wrong about this one.{/i}'"
    Rin "'{i} Kyousuke is happy with her, and I guess that's enough for me.  Thanks for trying Ringo, good luck with your next wish and your retirement.{/i}'"
    Rin "Wait? Nonononono, there's still time! Kanna, you idiot! You told me you didn't think Kyousuke was a good fit for Maya!"
    Rin "God, why are teenagers so wishy washy with their feelings!"

    Maya" Let's go play some of the booth games, Kyousuke!"
    Maya "I think you'd be a pretty good boyfriend if you won me a prize at one of the games~"
    Kyou "Win you a prize? Screw that, I want my own prize!"
    Maya "But wouldn't it be so romantic if you won one for me? You'd be like the king of romance."
    Maya "And being a king is so much better than keeping some silly prize. And the best kings are the most generous."
    Kyou "You're right! The king of romance would always give his stuff to his partner!"
    Maya "Atta boy Kyousuke!"
    Maya "After that, maybe you can come back to my house. We can start planning out all your time tonight so you don't have to worry about it later."
    Maya "Wouldn't that be a wonderful way to end Kumamatsuri?"
    Kyou "G-going to a girls house? Can I do that?"
    Maya "You've been to my house before when we walked your dog remember? Come on, let's go."

    Rin "Nononono, they can't leave until Kanna comes back!"
    Rin "I can't give up. I... I..."
    Rin "I…can't do anything without Kanna here. She's the wishmaker after all."
    # The sigh should be deep and sorrowful.
    Rin "{i}Siiiiggggghhhhh.{/i} Imagine that, a week of work gone for one wish. The millionth wish..."
    Rin "I could have completed like fifty wishes instead of this one. I guess I'm not as powerful as I thought..."
    Rin "Doing everything right, only to freakin' bungle it at the end."
    Rin "{i}Sigh.{/i} I guess, uh... I guess I better wait for the next person to make a wish on the shrine."
    Rin "I'm sorry Kanna, I really am."
    #Fade to black.
    #End


    #Choices for Kyousuke:
    #"One sec, I gotta use the bathroom."

    #Kanna Ending (Maya variant)

    Maya "Well, alright, just hurry back quickl-"
    Kyou "Don't worry, I won't be lo- Hey, is that Kanna over there?"
    Maya "What? No, of course not. Then again, all average girls look the same..."
    Kyou "No, I think that is Kanna! We should go say hi!"
    Maya "Kyousuke, no, come back here right now!"

   # Translation to Kyousuke going over to Kanna.
   # "Kyousuke stands up and walks over to Kanna's table."

    Kan "K-K-Kyousuke, hi! Didn't expect to s-see you here!"
    Kyou "Hi, Kanna! How are you? Are you here all by yourself?"
    Kan "W-well I-"
    Maya "Kanna! What do you think you're doing here? Spying on us?"
    Kan "N-no! I just really love the taiyaki here. The little fish shape is just so cute and all the different filings taste so good."
    Kyou "I know, right! I think my favorite are th-"
    Maya "Seriously? What a lame excuse. You're trying to mess with our date today, aren't you?"
    Kan "N-no! Seriously! And Kumamatsuri only happens once a year, I just had to come for the delicious food and the uh…atmosphere!"
    Maya "That's a load of bull and you know it. You don't have the guts to come here on your own and I know that Kanna. Who put you up to this? Charlotte?"
    Kan "..."
    Kyou "Hey, come on now, Maya, she's just trying to eat a delicious taiyaki. Just like we did!"
    Maya "So she's going to copy us now? She can't stand the fact she didn't get her way and now she has to pretend like she's with us and do the same things as use."
    Maya "Nice yukata. What, did you just have that old raggedy thing lying around and you just happen to be wearing a yukata like me?"
    Kan "W-wearing a yukata is tradition! What do you mean?"
    Kyou "It's alright Maya. Kanna is just here to celebrate like we are. You don't have to be so mean."
    Maya "You're telling me it's just a happy happenstance that you're here on the day we decided to go on a date? Really? Is that what you're telling me right now, Kanna?"
    Maya "You pulled some kind of magical mambo jumbo from your butt to deal with Charlotte, and now it's my turn right?"
    Maya "Because you can't handle the fact Kyousuke chose someone who wasn't you, even though I won him fair and square. He's mine."
    Maya "So now you're here to cheat your way in? Real mature. That must be why I never see you with anybody else. Do you even have friends? You know, no one likes a cheat, Kanna."
    Maya "I'm not gonna sit here and pretend you're not up to something to ruin our night. You should just go home, Kanna, no one wants you here anyway."
    Kan "..."
    Kan "You won him fair and square? Do you mean that? That's what you just said right?"
    Maya "What? Yes, that's what I just said, try listening next time."
    Kan "You don't win love Maya. Kyousuke isn't an object, he's a person - an amazing person who loves everyone with all his heart. Love is not something you force someone to do."
    Kan "Kyousuke should be with someone he really loves, and that person should love him back. And I don't think that person is you, Maya."
    Maya "Excuse me? Kyousuke chose {b}ME{/b} in the dumb letter, I literally just said that. Kyousuke is obedient, he knows he had to pick me."
    Maya "Just look at me! How could he even think to pick between your frumpy butt or Charlotte's messed up head? I'm the only real option."
    Maya "Besides I TOLD him to pick me at the end of the day. And he always listens to me, because I'm his childhood friend, he's obligated to do anything I say."
    Maya "So, like I already said, why don't you stuff your fat face with your fish cakes, and waddle on home? At least have some dignity in losing."
    Kyou "..."
    Kyou "Actually, Maya, I think you should go home. That's really mean and I think you need to cool off."
    Maya "What!?"
    Kyou "She's just here eating food, and you blew up on her. I don't think she's the bad guy here."
    Kan "..."
    Maya "..."
    Maya "Well, fine! Whatever! Fall for her dumb tricks then, Kyousuke. See how far you make it."

#Maya exits
   #"Maya stomps off in the opposite direction. "
    Kan "{i}Sniff.  Sniff. Waaaaaaaaa...{/i}"
    Kyou "Hey, it's alright."
    Kan "B-b-but everything she said was true! Kyousuke, I've bee-"
    Kyou "Hey, I don't care. And I don't think you're fat at all."
    Kan "N-no, not t-that. You s-should really know the t-truth."
    Kyou "The only truth I see and care about here is that you got one another taiyaki. You gonna eat that?"
    Kan "N-no. You can have it. I guess."
    Kyou "Sweetness! You know, eating something always clears my head and makes me feel better."
    Kyou "But it looks like you're all out of food. You still hungry?"
    Kan "Y-you just ate my taiyaki."
    Kyou "So, we need to go get something else to eat, right? You like sweet potatoes?"
    Kan "...yea."
    Kyou "Well, let's go! I'm sure that'll cheer you up Kanna!"
    Kan "But Kyousuke, I'm no better than Maya, I've been tricking you this who-"
    Kyou "Hey now, if we ain't talking about potatoes, it's not important."
    Kyou "Besides, I feel like Maya might have been the one messing with me this whole time, though I'm not sure how."
    Kyou "She doesn't even like dumplings or sweet potatoes ... I mean, come on, that's not human."
    Kan "But..."
    Kyou "No more buts, we've had enough crying and yelling today, let's just hang out for a while, ok?"
    Kan "I...alright. {i}Sniff.{/i} Let's go Kyousuke."

    Rin "It's funny how somethings work out. That arrogant girl dug her own grave."
    Rin "And gave my dumb girl a chance to just let things happen, I guess. Maybe Kyousuke isn't as stupid as I thought."
    Rin "Wait, does that moron even like Kanna or is he just hungry?"
    Rin "Doesn't matter, that's another wish granted!"
    Rin "My last wish, huh."

    #ART the screen slowly begins to fade into white.
    # SFX something angelic and subtle.

    Rin "What's happening?"
    Rin "My body is glowing."
    Rin "This feels amazing!"
    Rin "It's finally time! Oh baby, I've been waiting for this!"
    Rin "No more dumb fur. No more dumb romantic hijinks. Back to classic Ringo baby!"
    Rin "Guess I should have had more faith in the girl."
    Rin "Thank you, Kanna."
    scene black with fade
    #End
